# Generated by Django 5.2.4 on 2026-05-01 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('stat_card', 'Statistic Card'), ('chart', 'Chart'), ('table', 'Table'), ('list', 'List'), ('calendar', 'Calendar')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('data_source', models.CharField(max_length=100)),
                ('configuration', models.JSONField(default=dict)),
                ('refresh_interval', models.IntegerField(default=300, help_text='Refresh interval in seconds')),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_widgets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidgetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=1)),
                ('height', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dashboard.dashboardwidget')),
            ],
            options={
                'db_table': 'dashboard_widget_assignments',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserDashboardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dashboard_type', models.CharField(choices=[('hr', 'HR Dashboard'), ('team_leader', 'Team Leader Dashboard'), ('employee', 'Employee Dashboard')], max_length=20)),
                ('layout', models.JSONField(default=dict)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preferences', to=settings.AUTH_USER_MODEL)),
                ('widgets', models.ManyToManyField(through='dashboard.DashboardWidgetAssignment', to='dashboard.dashboardwidget')),
            ],
            options={
                'db_table': 'user_dashboard_preferences',
            },
        ),
        migrations.AddField(
            model_name='dashboardwidgetassignment',
            name='preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_assignments', to='dashboard.userdashboardpreference'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['widget_type'], name='dashboard_w_widget__47e2e7_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['is_active'], name='dashboard_w_is_acti_443f28_idx'),
        ),
        migrations.AddIndex(
            model_name='userdashboardpreference',
            index=models.Index(fields=['user'], name='user_dashbo_user_id_06d1a3_idx'),
        ),
        migrations.AddIndex(
            model_name='userdashboardpreference',
            index=models.Index(fields=['dashboard_type'], name='user_dashbo_dashboa_658869_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userdashboardpreference',
            unique_together={('user', 'dashboard_type')},
        ),
        migrations.AddIndex(
            model_name='dashboardwidgetassignment',
            index=models.Index(fields=['preference'], name='dashboard_w_prefere_41e315_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidgetassignment',
            index=models.Index(fields=['widget'], name='dashboard_w_widget__02675d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardwidgetassignment',
            unique_together={('preference', 'widget')},
        ),
    ]
