# Generated by Django 5.1.15 on 2026-05-09 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('leave_management', '0001_initial'),
        ('overtime', '0003_overtimelog_overtime_lo_client__aac471_idx_and_more'),
        ('permissions', '0002_permissionset_permissionsetitem'),
        ('standby', '0003_remove_standbypattern_standby_pat_pattern_2c737d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Display name for the calendar', max_length=100)),
                ('code', models.CharField(help_text='Unique code for the calendar', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color for calendar display', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Icon name for the calendar', max_length=50)),
                ('is_public', models.BooleanField(default=False, help_text='If true, all users can see this calendar')),
                ('default_view', models.CharField(choices=[('month', 'Month'), ('week', 'Week'), ('day', 'Day'), ('list', 'List')], default='month', max_length=20)),
                ('show_overtime', models.BooleanField(default=True)),
                ('show_standby', models.BooleanField(default=True)),
                ('show_leave', models.BooleanField(default=True)),
                ('show_holidays', models.BooleanField(default=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='Groups that can access this calendar', related_name='accessible_calendars', to='permissions.group')),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Specific users that can access this calendar', related_name='accessible_calendars', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar Workspace',
                'verbose_name_plural': 'Calendar Workspaces',
                'db_table': 'calendar_workspaces',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CalendarPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('permission', models.CharField(choices=[('view', 'View Calendar'), ('create_entries', 'Create Entries'), ('edit_own', 'Edit Own Entries'), ('edit_all', 'Edit All Entries'), ('delete_own', 'Delete Own Entries'), ('delete_all', 'Delete All Entries'), ('manage', 'Manage Calendar Settings')], max_length=30)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_permissions', to='permissions.group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_permissions', to=settings.AUTH_USER_MODEL)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='dashboard.calendarworkspace')),
            ],
            options={
                'db_table': 'calendar_permissions',
                'unique_together': {('calendar', 'group', 'permission'), ('calendar', 'user', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('entry_type', models.CharField(choices=[('overtime', 'Overtime'), ('standby', 'Standby'), ('leave', 'Leave'), ('holiday', 'Holiday'), ('custom', 'Custom Event')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('color', models.CharField(blank=True, help_text='Custom color for this entry', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='If set, this entry is for this specific user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_calendar_entries', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_calendar_entries', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('leave_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='leave_management.leaverequest')),
                ('overtime_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='overtime.overtimelog')),
                ('standby_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='standby.standbylog')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='dashboard.calendarworkspace')),
            ],
            options={
                'db_table': 'calendar_entries',
                'ordering': ['start_date', 'start_time'],
                'indexes': [models.Index(fields=['calendar', 'start_date'], name='calendar_en_calenda_136fd5_idx'), models.Index(fields=['entry_type', 'start_date'], name='calendar_en_entry_t_ab5f9d_idx'), models.Index(fields=['assigned_to', 'start_date'], name='calendar_en_assigne_082aed_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserCalendarPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show this calendar in the view')),
                ('is_default', models.BooleanField(default=False, help_text="This is the user's default calendar")),
                ('display_color', models.CharField(blank=True, help_text='Override calendar color', max_length=7)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Order in the calendar list')),
                ('show_only_my_entries', models.BooleanField(default=False, help_text='Only show entries created by me')),
                ('show_only_my_team', models.BooleanField(default=False, help_text='Only show entries from my team')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='dashboard.calendarworkspace')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_calendar_preferences',
                'ordering': ['sort_order', 'calendar__name'],
                'unique_together': {('user', 'calendar')},
            },
        ),
    ]
