# Generated by Django 5.1.15 on 2026-05-11 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_calendarworkspace_calendarpermission_calendarentry_and_more'),
        ('permissions', '0002_permissionset_permissionsetitem'),
        ('users', '0008_teammembership_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarworkspace',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Primary team for this workspace (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_workspaces', to='users.team'),
        ),
        migrations.AddIndex(
            model_name='calendarworkspace',
            index=models.Index(fields=['team'], name='calendar_wo_team_id_f6cd1d_idx'),
        ),
    ]
