# Generated by Django 5.1.15 on 2026-06-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_publicholiday_deleted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdashboardpreference',
            name='dashboard_type',
            field=models.CharField(choices=[('hr', 'HR Dashboard'), ('team_leader', 'Team Leader Dashboard'), ('employee', 'Employee Dashboard'), ('admin', 'Admin Dashboard')], max_length=20),
        ),
    ]
