# Generated by Django 5.1.15 on 2026-08-05 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_calendarworkspace_allowed_groups'),
        ('leave_management', '0007_globalsettings_leave_global_settings_singleton'),
        ('overtime', '0004_alter_overtimelog_calculated_wage_and_more'),
        ('standby', '0006_alter_standbylog_calculated_wage_and_more'),
        ('users', '0012_alter_userprofile_role_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='calendarentry',
            index=models.Index(fields=['status'], name='calendar_en_status_5177f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarworkspace',
            constraint=models.UniqueConstraint(fields=('name',), name='calendar_workspace_name_unique'),
        ),
    ]
