# Generated by Django 5.2.4 on 2026-08-17 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_make_team_calendars_private'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='publicholiday',
            constraint=models.UniqueConstraint(
                condition=models.Q(calendar__isnull=True),
                fields=('date', 'country_code'),
                name='public_holiday_global_date_country_unique',
            ),
        ),
        migrations.DeleteModel(
            name='CalendarEntry',
        ),
        migrations.DeleteModel(
            name='CalendarPermission',
        ),
    ]
