# Generated by Django 5.1.15 on 2026-05-09 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('default_yearly_leave_days', models.DecimalField(decimal_places=1, default=22.0, help_text='Default leave days per year for new users', max_digits=5)),
                ('carry_over_expiry_month', models.PositiveSmallIntegerField(default=3, help_text='Month when carried-over days expire (1-12, default 3 = March)')),
                ('carry_over_expiry_day', models.PositiveSmallIntegerField(default=31, help_text='Day of the month when carried-over days expire (default 31)')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave_global_settings',
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('leave_type', models.CharField(choices=[('leave', 'Leave'), ('sick', 'Sick Leave')], max_length=20)),
                ('year', models.IntegerField()),
                ('total_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('used_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('pending_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('is_carry_over', models.BooleanField(db_index=True, default=False, help_text='True if this balance was carried over from previous year')),
                ('expires_at', models.DateField(blank=True, help_text='Carry-over expiry date (e.g. March 31)', null=True)),
                ('accrual_start_date', models.DateField(blank=True, help_text='Date from which monthly accrual starts (usually hire_date)', null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave_balances',
                'ordering': ['user', '-year', 'leave_type'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('request_type', models.CharField(choices=[('leave', 'Leave'), ('sick', 'Sick Leave')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='leave_management.leavebalance')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave_requests',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['user', 'year'], name='leave_balan_user_id_3b7d73_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['leave_type'], name='leave_balan_leave_t_b4fa1a_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['is_carry_over'], name='leave_balan_is_carr_a9efff_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['expires_at'], name='leave_balan_expires_6d126e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('user', 'leave_type', 'year', 'is_carry_over')},
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['user', 'status'], name='leave_reque_user_id_487b5f_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['start_date'], name='leave_reque_start_d_e77766_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['end_date'], name='leave_reque_end_dat_2a73ee_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['request_type'], name='leave_reque_request_4c5ac2_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status'], name='leave_reque_status_401183_idx'),
        ),
    ]
