# Generated by Django 5.2.4 on 2026-05-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0002_alter_leavebalance_leave_type_and_more'),
        ('leave_management', '0002_set_hire_date_for_existing_users'),
    ]

    operations = [
    ]
