# Generated by Django 5.1.15 on 2026-05-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_merge_20260518_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_type',
            field=models.CharField(choices=[('vacation', 'Vacation'), ('sick', 'Sick Leave'), ('holiday', 'Holiday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='request_type',
            field=models.CharField(choices=[('vacation', 'Vacation'), ('sick', 'Sick Leave'), ('holiday', 'Holiday')], max_length=20),
        ),
    ]
