# Generated by Django 5.1.15 on 2026-05-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0004_alter_leavebalance_leave_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_type',
            field=models.CharField(choices=[('vacation', 'Vacation'), ('sick', 'Sick Leave')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='request_type',
            field=models.CharField(choices=[('vacation', 'Vacation'), ('sick', 'Sick Leave')], max_length=20),
        ),
    ]
