# Generated by Django 5.1.15 on 2026-06-01 08:08

from django.db import migrations, models


def delete_sick_balances(apps, schema_editor):
    """Delete all sick leave balance records before removing the choice."""
    LeaveBalance = apps.get_model('leave_management', 'LeaveBalance')
    LeaveBalance.objects.filter(leave_type='sick').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0005_alter_leavebalance_leave_type_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_sick_balances, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_type',
            field=models.CharField(choices=[('vacation', 'Vacation')], max_length=20),
        ),
    ]
