# Generated by Django 5.1.15 on 2026-08-05 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0006_remove_sick_from_balance_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='globalsettings',
            constraint=models.CheckConstraint(condition=models.Q(('pk', 1)), name='leave_global_settings_singleton'),
        ),
    ]
