# Generated by Django 5.2.17 on 2026-09-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0007_globalsettings_leave_global_settings_singleton'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='submitted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
