# Generated by Django 5.2.4 on 2026-07-07 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_key', models.CharField(max_length=50)),
                ('field_mapping', models.JSONField(default=dict, help_text="Map our normalized fields to the uploaded file's column names")),
                ('default_values', models.JSONField(default=dict, help_text='Fixed default values for unmapped fields')),
                ('options', models.JSONField(default=dict, help_text='Importer options (update_existing, password_strategy, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_import_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_import_profiles',
                'ordering': ['name'],
                'unique_together': {('name', 'target_key')},
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_key', models.CharField(max_length=50)),
                ('original_filename', models.CharField(max_length=255)),
                ('field_mapping_used', models.JSONField(default=dict)),
                ('options_used', models.JSONField(default=dict)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('row_errors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_import_batches', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='data_import.importprofile')),
            ],
            options={
                'db_table': 'data_import_batches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_key'], name='data_import_target__1fb7d3_idx'), models.Index(fields=['created_at'], name='data_import_created_639964_idx')],
            },
        ),
    ]
