# Generated by Django 5.2.17 on 2026-09-10 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='backups/')),
                ('filename', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(help_text='SHA-256 hex digest of the archive file.', max_length=64)),
                ('migration_state_hash', models.CharField(help_text='SHA-256 of the applied-migrations set at backup time, used to block restore onto an incompatible schema.', max_length=64)),
                ('db_row_count', models.PositiveIntegerField(default=0, help_text='Total DB rows captured across all dumped models.')),
                ('media_file_count', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'site_backup_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
