# Generated by Django 5.1.15 on 2026-06-15 18:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('field_mapping', models.JSONField(default=dict, help_text="Map our normalized fields to the user's export column names")),
                ('value_transforms', models.JSONField(default=dict, help_text='Transform raw values to normalized values per field')),
                ('required_fields', models.JSONField(default=list, help_text='List of our field names that must be present in every upload')),
                ('compute_resolution_time', models.BooleanField(default=True, help_text='Auto-calculate time_to_resolution_hours from created_at and resolved_at')),
                ('compute_sla', models.BooleanField(default=False, help_text='Auto-determine sla_breached from SLA column or resolution time')),
                ('is_global', models.BooleanField(default=False, help_text='If true, this profile is available to all users as a fallback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ticket_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export Profile',
                'verbose_name_plural': 'Export Profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TicketImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month this upload represents')),
                ('raw_file', models.FileField(help_text='Original uploaded file (CSV or Excel)', upload_to='ticket_imports/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx', 'xls'])])),
                ('record_count', models.PositiveIntegerField(default=0, help_text='Number of successfully parsed records')),
                ('is_overridden', models.BooleanField(default=False, help_text='Set to true when user re-uploads for the same month')),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_ticket_batches', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='ticket_kpi.exportprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket Import Batch',
                'verbose_name_plural': 'Ticket Import Batches',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(db_index=True, max_length=100)),
                ('title', models.TextField()),
                ('status', models.CharField(db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('assignee', models.CharField(blank=True, db_index=True, max_length=200)),
                ('requester', models.CharField(blank=True, max_length=200)),
                ('priority', models.CharField(blank=True, db_index=True, max_length=50)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('time_to_resolution_hours', models.FloatField(blank=True, help_text='Hours between created_at and resolved_at', null=True)),
                ('sla_breached', models.BooleanField(blank=True, help_text='True if SLA was breached (from export column or computed)', null=True)),
                ('raw_data', models.JSONField(default=dict, help_text='All columns from the original export not mapped to normalized fields')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticket_kpi.ticketimportbatch')),
            ],
            options={
                'verbose_name': 'Normalized Ticket',
                'verbose_name_plural': 'Normalized Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month')),
                ('total_tickets', models.PositiveIntegerField(default=0)),
                ('closed_tickets', models.PositiveIntegerField(default=0)),
                ('open_tickets', models.PositiveIntegerField(default=0)),
                ('avg_resolution_hours', models.FloatField(blank=True, help_text='Average resolution time in hours (excludes unresolved)', null=True)),
                ('min_resolution_hours', models.FloatField(blank=True, null=True)),
                ('max_resolution_hours', models.FloatField(blank=True, null=True)),
                ('sla_compliance_pct', models.FloatField(blank=True, help_text='Percentage of tickets where sla_breached=false', null=True)),
                ('sla_breached_count', models.PositiveIntegerField(default=0)),
                ('by_category', models.JSONField(default=dict, help_text='{category_name: count}')),
                ('by_priority', models.JSONField(default=dict, help_text='{priority_name: count}')),
                ('by_status', models.JSONField(default=dict, help_text='{status_name: count}')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_kpis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly KPI',
                'verbose_name_plural': 'Monthly KPIs',
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['user', 'month'], name='ticket_kpi__user_id_25b56e_idx')],
                'unique_together': {('user', 'month')},
            },
        ),
        migrations.AddIndex(
            model_name='ticketimportbatch',
            index=models.Index(fields=['user', 'month'], name='ticket_kpi__user_id_60788f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketimportbatch',
            index=models.Index(fields=['profile'], name='ticket_kpi__profile_0acc6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketimportbatch',
            unique_together={('user', 'month')},
        ),
        migrations.AddIndex(
            model_name='normalizedticket',
            index=models.Index(fields=['batch', 'status'], name='ticket_kpi__batch_i_13126c_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedticket',
            index=models.Index(fields=['batch', 'category'], name='ticket_kpi__batch_i_dfefd1_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedticket',
            index=models.Index(fields=['batch', 'priority'], name='ticket_kpi__batch_i_1c361e_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedticket',
            index=models.Index(fields=['batch', 'assignee'], name='ticket_kpi__batch_i_559725_idx'),
        ),
    ]
