# Generated by Django 5.1.15 on 2026-06-19 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0003_overtimelog_overtime_lo_client__aac471_idx_and_more'),
        ('ticket_kpi', '0002_seed_default_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlykpi',
            name='field_breakdowns',
            field=models.JSONField(default=dict, help_text='{field_name: {value: count}} for every distinct field found in uploads'),
        ),
        migrations.AddField(
            model_name='normalizedticket',
            name='row_index',
            field=models.PositiveIntegerField(default=0, help_text='Original row number in the uploaded file'),
        ),
        migrations.AddField(
            model_name='ticketimportbatch',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='ticket_import_batches', to='overtime.client'),
        ),
        migrations.AddField(
            model_name='ticketimportbatch',
            name='detected_columns',
            field=models.JSONField(default=list, help_text='List of column names found in the uploaded file'),
        ),
        migrations.AddField(
            model_name='ticketimportbatch',
            name='detected_field_map',
            field=models.JSONField(default=dict, help_text='Map of canonical field -> detected column name'),
        ),
        migrations.AlterField(
            model_name='normalizedticket',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='normalizedticket',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='normalizedticket',
            name='priority',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='normalizedticket',
            name='raw_data',
            field=models.JSONField(default=dict, help_text='Complete row data from the uploaded file (all columns)'),
        ),
        migrations.AlterField(
            model_name='normalizedticket',
            name='status',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='normalizedticket',
            name='ticket_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='normalizedticket',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticketimportbatch',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='ticket_kpi.exportprofile'),
        ),
    ]
