# Generated by Django 5.2.4 on 2026-07-18 17:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0003_overtimelog_overtime_lo_client__aac471_idx_and_more'),
        ('ticket_kpi', '0007_ticketimportbatch_reviewed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month this evidence applies to')),
                ('evidence_type', models.CharField(choices=[('document', 'Document'), ('certificate', 'Certificate'), ('email_thread', 'Email Thread'), ('screenshot', 'Screenshot'), ('other', 'Other')], default='document', max_length=20)),
                ('file', models.FileField(help_text='Evidence file (PDF, image, email, text, HTML)', upload_to='kpi_evidence/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'eml', 'msg', 'txt', 'html', 'htm'])])),
                ('description', models.TextField(blank=True, help_text='Optional description/context for the evidence')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('parsed_email', models.JSONField(blank=True, default=dict, help_text='Structured email preview (sender, date, subject, body, attachments)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clients', models.ManyToManyField(blank=True, related_name='ticket_kpi_evidence', to='overtime.client')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ticket_kpi_evidence', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_kpi_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KPI Evidence',
                'verbose_name_plural': 'KPI Evidence',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'month'], name='ticket_kpi__user_id_66771a_idx'), models.Index(fields=['status'], name='ticket_kpi__status_cb2e5c_idx'), models.Index(fields=['evidence_type'], name='ticket_kpi__evidenc_5e1a2f_idx')],
            },
        ),
    ]
