# Generated by Django 5.1.15 on 2026-08-05 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0004_alter_overtimelog_calculated_wage_and_more'),
        ('ticket_kpi', '0010_alter_kpievidence_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exportprofile',
            constraint=models.UniqueConstraint(fields=('name',), name='export_profile_name_unique'),
        ),
    ]
