# Generated by Django 5.2.4 on 2026-08-11 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0007_remove_unique_overtime_per_day_client'),
        ('ticket_kpi', '0011_exportprofile_export_profile_name_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketOvertimeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('link_method', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='manual', max_length=10)),
                ('review_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='confirmed', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('linked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_links_created', to=settings.AUTH_USER_MODEL)),
                ('normalized_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_links', to='ticket_kpi.normalizedticket')),
                ('overtime_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_links', to='overtime.overtimelog')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_links_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket_kpi_overtime_links',
                'ordering': ['-linked_at'],
                'indexes': [models.Index(fields=['review_status'], name='ticket_kpi__review__b5e262_idx'), models.Index(fields=['link_method'], name='ticket_kpi__link_me_5cd77f_idx')],
                'constraints': [models.UniqueConstraint(fields=('overtime_log', 'normalized_ticket'), name='unique_ticket_overtime_link')],
            },
        ),
    ]
