# Generated by Django 5.2.4 on 2026-08-21 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_kpi', '0012_ticketovertimelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpievidence',
            name='file',
            field=models.FileField(help_text='Evidence file (PDF, image, email, text, Office doc)', upload_to='kpi_evidence/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'eml', 'msg', 'txt', 'doc', 'docx', 'xls', 'xlsx', 'csv'])]),
        ),
    ]
