# Generated by Django 5.1.15 on 2026-05-09 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0002_add_time_fields_and_evidence_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='overtimelog',
            index=models.Index(fields=['client', 'status'], name='overtime_lo_client__aac471_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimelog',
            index=models.Index(fields=['user', 'status', 'date'], name='overtime_lo_user_id_bc31e1_idx'),
        ),
    ]
