# Generated by Django 5.2.4 on 2026-08-09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0006_overtimelog_approval_period_close_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='overtimelog',
            name='unique_overtime_per_day_client',
        ),
    ]
