# Generated by Django 5.2.4 on 2026-08-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0007_remove_unique_overtime_per_day_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimelog',
            name='ticket_references',
            field=models.JSONField(blank=True, default=list, help_text='Structured ticket references; maximum 20 entries.'),
        ),
    ]
