# Generated by Django 5.2.4 on 2026-08-17 14:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permissions', '0005_remove_dormant_rbac'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('source_mode', models.CharField(choices=[('live', 'live'), ('custom', 'custom')], default='custom', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('archived', 'archived')], default='draft', max_length=20)),
                ('audience_mode', models.CharField(choices=[('all_authenticated', 'all_authenticated'), ('selected', 'selected'), ('private_admin', 'private_admin')], default='private_admin', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('revision_number', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orgcharts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_orgcharts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organigrama_orgchart',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OrgChartNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('shape_type', models.CharField(choices=[('person', 'person'), ('position', 'position'), ('vacant', 'vacant'), ('external', 'external'), ('department', 'department'), ('division', 'division'), ('team', 'team'), ('location', 'location'), ('label', 'label'), ('section', 'section'), ('placeholder', 'placeholder')], max_length=20)),
                ('display_name', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('role_title', models.CharField(blank=True, default='', max_length=100)),
                ('department_label', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'active'), ('vacant', 'vacant'), ('planned', 'planned'), ('archived', 'archived')], default='active', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('width', models.PositiveIntegerField(default=180)),
                ('height', models.PositiveIntegerField(default=80)),
                ('style_key', models.CharField(blank=True, default='', max_length=40)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('is_searchable', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='organigrama.orgchart')),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_orgchart_nodes', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organigrama.orgchartnode')),
            ],
            options={
                'db_table': 'organigrama_orgchartnode',
                'ordering': ['chart', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrgChartEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('edge_type', models.CharField(choices=[('reports_to', 'reports_to'), ('dotted_line', 'dotted_line'), ('assistant', 'assistant'), ('association', 'association'), ('contains', 'contains')], max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('style_key', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='organigrama.orgchart')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='organigrama.orgchartnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='organigrama.orgchartnode')),
            ],
            options={
                'db_table': 'organigrama_orgchartedge',
                'ordering': ['chart', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrgChartRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('payload', models.JSONField()),
                ('checksum', models.CharField(max_length=64)),
                ('change_summary', models.TextField(blank=True, default='')),
                ('schema_version', models.CharField(default='1', max_length=20)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='organigrama.orgchart')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_orgchart_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organigrama_orgchartrevision',
                'ordering': ['chart', '-version'],
            },
        ),
        migrations.AddField(
            model_name='orgchart',
            name='published_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_for_chart', to='organigrama.orgchartrevision'),
        ),
        migrations.CreateModel(
            name='OrgChartAudienceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_groups', to='organigrama.orgchart')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgchart_audiences', to='permissions.group')),
            ],
            options={
                'db_table': 'organigrama_orgchartaudiencegroup',
                'indexes': [models.Index(fields=['chart', 'group'], name='organigrama_chart_i_248a95_idx')],
                'constraints': [models.UniqueConstraint(fields=('chart', 'group'), name='audience_group_unique')],
            },
        ),
        migrations.CreateModel(
            name='OrgChartAudienceRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_code', models.CharField(choices=[('employee', 'employee'), ('italian_tl', 'italian_tl'), ('albanian_tl', 'albanian_tl'), ('hr', 'hr'), ('cr_admin', 'cr_admin')], max_length=20)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_roles', to='organigrama.orgchart')),
            ],
            options={
                'db_table': 'organigrama_orgchartaudiencerole',
                'indexes': [models.Index(fields=['chart', 'role_code'], name='organigrama_chart_i_aec2d8_idx')],
                'constraints': [models.UniqueConstraint(fields=('chart', 'role_code'), name='audience_role_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='orgchartnode',
            index=models.Index(fields=['chart', 'parent'], name='organigrama_chart_i_460ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='orgchartnode',
            index=models.Index(fields=['chart', 'shape_type'], name='organigrama_chart_i_6ddb62_idx'),
        ),
        migrations.AddIndex(
            model_name='orgchartnode',
            index=models.Index(fields=['chart', 'linked_user'], name='organigrama_chart_i_103e26_idx'),
        ),
        migrations.AddConstraint(
            model_name='orgchartnode',
            constraint=models.UniqueConstraint(fields=('chart', 'node_uuid'), name='node_uuid_unique_per_chart'),
        ),
        migrations.AddIndex(
            model_name='orgchartedge',
            index=models.Index(fields=['chart', 'source'], name='organigrama_chart_i_a03889_idx'),
        ),
        migrations.AddIndex(
            model_name='orgchartedge',
            index=models.Index(fields=['chart', 'target'], name='organigrama_chart_i_dd3cfd_idx'),
        ),
        migrations.AddConstraint(
            model_name='orgchartedge',
            constraint=models.UniqueConstraint(fields=('chart', 'edge_uuid'), name='edge_uuid_unique_per_chart'),
        ),
        migrations.AddConstraint(
            model_name='orgchartedge',
            constraint=models.UniqueConstraint(fields=('chart', 'source', 'target', 'edge_type'), name='edge_unique_per_chart_pair_type'),
        ),
        migrations.AddIndex(
            model_name='orgchartrevision',
            index=models.Index(fields=['chart', 'version'], name='organigrama_chart_i_7c8ae3_idx'),
        ),
        migrations.AddIndex(
            model_name='orgchartrevision',
            index=models.Index(fields=['chart', 'published_at'], name='organigrama_chart_i_15f453_idx'),
        ),
        migrations.AddConstraint(
            model_name='orgchartrevision',
            constraint=models.UniqueConstraint(fields=('chart', 'version'), name='revision_version_unique'),
        ),
        migrations.AddIndex(
            model_name='orgchart',
            index=models.Index(fields=['status'], name='organigrama_status_5fc3d5_idx'),
        ),
        migrations.AddIndex(
            model_name='orgchart',
            index=models.Index(fields=['source_mode'], name='organigrama_source__9632c8_idx'),
        ),
        migrations.AddIndex(
            model_name='orgchart',
            index=models.Index(fields=['is_featured'], name='organigrama_is_feat_faac41_idx'),
        ),
    ]
