# Generated by Django 5.2.4 on 2026-08-17 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigrama', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orgchartedge',
            index=models.Index(fields=['chart', 'sort_order'], name='organigrama_chart_i_4f6dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='orgchartnode',
            index=models.Index(fields=['chart', 'sort_order'], name='organigrama_chart_i_cdd44a_idx'),
        ),
    ]
