# Generated by Django 5.2.4 on 2026-08-17 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigrama', '0002_orgchartedge_organigrama_chart_i_4f6dd6_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orgchart',
            index=models.Index(fields=['status', 'audience_mode'], name='organigrama_status_731080_idx'),
        ),
    ]
