# Generated by Django 5.2.4 on 2026-08-18 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigrama', '0003_orgchart_organigrama_status_731080_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orgchartnode',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grouped_nodes', to='organigrama.orgchartnode'),
        ),
        migrations.AddIndex(
            model_name='orgchartnode',
            index=models.Index(fields=['chart', 'group'], name='organigrama_chart_i_5e6b5c_idx'),
        ),
    ]
