# Generated by Django 5.2.4 on 2026-08-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organigrama', '0004_orgchartnode_group_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orgchartnode',
            name='organigrama_chart_i_460ce0_idx',
        ),
        migrations.RemoveField(
            model_name='orgchartnode',
            name='parent',
        ),
    ]
