# Generated by Django 5.1.15 on 2026-08-07 17:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('ALL', 'Albanian Lek'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='ALL', max_length=3, verbose_name='Currency')),
                ('country', models.CharField(choices=[('AL', 'Albania')], default='AL', max_length=2, verbose_name='Country')),
                ('default_tax_profile', models.CharField(default='standard', help_text='Tax profile code applied when a user has no explicit profile.', max_length=30, verbose_name='Default Tax Profile')),
                ('rounding_mode', models.CharField(choices=[('half_up', 'Round half up'), ('half_even', 'Round half even (banker)'), ('down', 'Round down (truncate)')], default='half_up', max_length=20, verbose_name='Rounding Mode')),
                ('rounding_precision', models.PositiveSmallIntegerField(default=0, help_text='Decimal places for final amounts. 0 = whole Lek.', verbose_name='Rounding Precision')),
                ('default_standby_hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Lek per hour for standby time.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Default Standby Hourly Rate')),
                ('monthly_hours_strategy', models.CharField(choices=[('fixed_174', 'Fixed 174 hours/month'), ('workdays_x8', 'Working days × 8 hours'), ('calendar_days', 'Calendar days × 8 hours')], default='fixed_174', max_length=20, verbose_name='Monthly Hours Strategy')),
                ('default_workday_hours', models.DecimalField(decimal_places=2, default=Decimal('8'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Default Workday Hours')),
                ('only_approved_entries', models.BooleanField(default=True, help_text='If true, only approved overtime/standby are included in payroll.', verbose_name='Only Approved Entries')),
                ('missing_timestamp_fallback_category', models.CharField(default='weekday_day', help_text='Overtime category used when start/end times are missing.', max_length=30, verbose_name='Missing Timestamp Fallback Category')),
                ('organization_name', models.CharField(blank=True, max_length=200, verbose_name='Organization Name')),
                ('payslip_footer', models.TextField(blank=True, help_text='Optional text shown at the bottom of payslip PDFs.', verbose_name='Payslip Footer')),
                ('rules_source_label', models.CharField(blank=True, help_text='Human-readable label for the rule source, e.g. "Boshti reference 2026".', max_length=200, verbose_name='Rules Source Label')),
                ('rules_validation_status', models.CharField(default='reference', help_text='Status of rule validation: reference, verified, official.', max_length=30, verbose_name='Rules Validation Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payroll Configuration',
                'verbose_name_plural': 'Payroll Configuration',
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='payroll_configuration_singleton')],
            },
        ),
        migrations.CreateModel(
            name='PayrollRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Version')),
                ('country', models.CharField(default='AL', max_length=2, verbose_name='Country')),
                ('effective_from', models.DateField(db_index=True, verbose_name='Effective From')),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True, verbose_name='Effective To')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('tax_profile', models.CharField(choices=[('standard', 'Standard employee'), ('category_6', 'Category 6 (reserved)'), ('category_7', 'Category 7 (reserved)')], default='standard', max_length=30, verbose_name='Tax Profile')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Source')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('validation_status', models.CharField(default='reference', help_text='reference, verified, or official.', max_length=30, verbose_name='Validation Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payroll Rule Set',
                'verbose_name_plural': 'Payroll Rule Sets',
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['effective_from', 'effective_to'], name='payroll_pay_effecti_93f849_idx'), models.Index(fields=['is_active', 'effective_from'], name='payroll_pay_is_acti_9a08a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True, verbose_name='Year')),
                ('month', models.PositiveSmallIntegerField(db_index=True, verbose_name='Month')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('configuration_snapshot', models.JSONField(default=dict, editable=False, help_text='PayrollConfiguration values captured at generation time.', verbose_name='Configuration Snapshot')),
                ('totals', models.JSONField(blank=True, default=dict, help_text='Run-level totals: gross, deductions, net, employer cost.', verbose_name='Totals')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalized At')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_runs', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_payroll_runs', to=settings.AUTH_USER_MODEL)),
                ('rule_set', models.ForeignKey(help_text='Rule set snapshot used for this run.', on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='payroll.payrollruleset')),
            ],
            options={
                'verbose_name': 'Payroll Run',
                'verbose_name_plural': 'Payroll Runs',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='PayrollTaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_bound', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monthly taxable income lower bound (Lek).', max_digits=12, verbose_name='Lower Bound')),
                ('upper_bound', models.DecimalField(blank=True, decimal_places=2, help_text='Null = no upper cap.', max_digits=12, null=True, verbose_name='Upper Bound')),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Tax rate as a fraction (0.13 = 13%).', max_digits=6, verbose_name='Rate')),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Fixed Lek amount added for this bracket.', max_digits=12, verbose_name='Fixed Amount')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_brackets', to='payroll.payrollruleset')),
            ],
            options={
                'verbose_name': 'Payroll Tax Bracket',
                'verbose_name_plural': 'Payroll Tax Brackets',
                'ordering': ['rule_set', 'order', 'lower_bound'],
            },
        ),
        migrations.CreateModel(
            name='PayrollWorkCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='AL', max_length=2, verbose_name='Country')),
                ('year', models.PositiveSmallIntegerField(db_index=True, verbose_name='Year')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payroll Work Calendar',
                'verbose_name_plural': 'Payroll Work Calendars',
                'ordering': ['-year'],
                'indexes': [models.Index(fields=['country', 'year'], name='payroll_pay_country_808a80_idx')],
                'constraints': [models.UniqueConstraint(fields=('country', 'year'), name='payroll_work_calendar_country_year_unique')],
            },
        ),
        migrations.CreateModel(
            name='PayrollWorkday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('is_working_day', models.BooleanField(db_index=True, default=True, verbose_name='Working Day')),
                ('is_holiday', models.BooleanField(db_index=True, default=False, verbose_name='Holiday')),
                ('holiday_name', models.CharField(blank=True, max_length=150, verbose_name='Holiday Name')),
                ('standard_hours', models.DecimalField(decimal_places=2, default=Decimal('8'), max_digits=5, verbose_name='Standard Hours')),
                ('override_note', models.CharField(blank=True, max_length=255, verbose_name='Override Note')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='payroll.payrollworkcalendar')),
            ],
            options={
                'verbose_name': 'Payroll Workday',
                'verbose_name_plural': 'Payroll Workdays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='WageAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_monthly_wage', models.DecimalField(decimal_places=2, help_text='Gross monthly wage in the configured currency (Lek).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Gross Monthly Wage')),
                ('effective_from', models.DateField(db_index=True, verbose_name='Effective From')),
                ('effective_to', models.DateField(blank=True, db_index=True, help_text='Leave blank for an open-ended wage. Must be ≥ effective_from.', null=True, verbose_name='Effective To')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wage_assignments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_wage_assignments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Employee receiving this gross monthly wage.', on_delete=django.db.models.deletion.CASCADE, related_name='wage_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wage Assignment',
                'verbose_name_plural': 'Wage Assignments',
                'ordering': ['user__username', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_monthly_wage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Gross Monthly Wage')),
                ('monthly_working_days', models.PositiveSmallIntegerField(default=0, verbose_name='Monthly Working Days')),
                ('monthly_standard_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Monthly Standard Hours')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Overtime Hours')),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Overtime Amount')),
                ('standby_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Standby Hours')),
                ('standby_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Standby Amount')),
                ('total_gross', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Total Gross')),
                ('taxable_base', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Taxable Base')),
                ('contribution_base', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Contribution Base')),
                ('employee_social', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Employee Social')),
                ('employee_health', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Employee Health')),
                ('income_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Income Tax')),
                ('total_employee_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Total Employee Deductions')),
                ('net_pay', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Net Pay')),
                ('employer_social', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Employer Social')),
                ('employer_health', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Employer Health')),
                ('total_employer_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Total Employer Cost')),
                ('overtime_breakdown', models.JSONField(blank=True, default=dict, help_text='Per-category overtime hours and amounts.', verbose_name='Overtime Breakdown')),
                ('calculation_trace', models.JSONField(blank=True, default=dict, help_text='Detailed calculation steps for audit.', verbose_name='Calculation Trace')),
                ('warnings', models.JSONField(blank=True, default=list, help_text='List of calculation warnings (missing timestamps, fallbacks, etc.).', verbose_name='Warnings')),
                ('rule_set_version', models.CharField(blank=True, max_length=20, verbose_name='Rule Set Version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_lines', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payrollrun')),
                ('wage_assignment', models.ForeignKey(blank=True, help_text='Wage assignment snapshot used for this line.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_lines', to='payroll.wageassignment')),
            ],
            options={
                'verbose_name': 'Payroll Line',
                'verbose_name_plural': 'Payroll Lines',
                'ordering': ['run', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='PayrollOvertimeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('weekday_day', 'Weekday daytime'), ('weekday_night', 'Weekday night'), ('weekend_day', 'Weekend daytime'), ('weekend_night', 'Weekend night'), ('holiday', 'Public holiday')], max_length=30, verbose_name='Code')),
                ('multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.25'), help_text='Multiplier applied to base hourly rate (1.25 = 125%).', max_digits=5, verbose_name='Multiplier')),
                ('night_start_hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('night_end_hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('applies_weekend', models.BooleanField(default=False)),
                ('applies_holiday', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_categories', to='payroll.payrollruleset')),
            ],
            options={
                'verbose_name': 'Payroll Overtime Category',
                'verbose_name_plural': 'Payroll Overtime Categories',
                'ordering': ['rule_set', 'order', 'code'],
                'indexes': [models.Index(fields=['rule_set'], name='payroll_pay_rule_se_066756_idx')],
                'constraints': [models.UniqueConstraint(fields=('rule_set', 'code'), name='payroll_overtime_category_unique_per_set_code')],
            },
        ),
        migrations.CreateModel(
            name='PayrollContributionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(choices=[('social', 'Social security'), ('health', 'Health insurance')], max_length=10, verbose_name='Type')),
                ('side', models.CharField(choices=[('employee', 'Employee'), ('employer', 'Employer')], max_length=10, verbose_name='Side')),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Fraction (0.095 = 9.5%).', max_digits=6, verbose_name='Rate')),
                ('cap', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum contribution base (Lek). Null = no cap.', max_digits=12, null=True, verbose_name='Cap')),
                ('floor', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum contribution base (Lek). Null = no floor.', max_digits=12, null=True, verbose_name='Floor')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_rates', to='payroll.payrollruleset')),
            ],
            options={
                'verbose_name': 'Payroll Contribution Rate',
                'verbose_name_plural': 'Payroll Contribution Rates',
                'ordering': ['rule_set', 'contribution_type', 'side'],
                'indexes': [models.Index(fields=['rule_set', 'contribution_type', 'side'], name='payroll_pay_rule_se_11a252_idx')],
                'constraints': [models.UniqueConstraint(fields=('rule_set', 'contribution_type', 'side'), name='payroll_contribution_unique_per_set_type_side')],
            },
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['year', 'month'], name='payroll_pay_year_8e8603_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['status'], name='payroll_pay_status_5e02ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'finalized')), fields=('year', 'month'), name='payroll_run_one_finalized_per_period'),
        ),
        migrations.AddIndex(
            model_name='payrolltaxbracket',
            index=models.Index(fields=['rule_set'], name='payroll_pay_rule_se_699e05_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollworkday',
            index=models.Index(fields=['calendar', 'date'], name='payroll_pay_calenda_c15c1a_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollworkday',
            index=models.Index(fields=['date', 'is_working_day'], name='payroll_pay_date_9c3df0_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollworkday',
            constraint=models.UniqueConstraint(fields=('calendar', 'date'), name='payroll_workday_calendar_date_unique'),
        ),
        migrations.AddIndex(
            model_name='wageassignment',
            index=models.Index(fields=['user', 'effective_from'], name='payroll_wag_user_id_34b69b_idx'),
        ),
        migrations.AddIndex(
            model_name='wageassignment',
            index=models.Index(fields=['user', 'effective_to'], name='payroll_wag_user_id_033628_idx'),
        ),
        migrations.AddIndex(
            model_name='wageassignment',
            index=models.Index(fields=['is_active'], name='payroll_wag_is_acti_fefce9_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollline',
            index=models.Index(fields=['run', 'user'], name='payroll_pay_run_id_f4c55a_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollline',
            index=models.Index(fields=['user'], name='payroll_pay_user_id_f32dea_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollline',
            constraint=models.UniqueConstraint(fields=('run', 'user'), name='payroll_line_run_user_unique'),
        ),
    ]
