# Generated by Django 5.1.15 on 2026-08-07 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payrollrun',
            name='payroll_run_one_finalized_per_period',
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'finalized'])), fields=('year', 'month'), name='payroll_run_one_active_per_period'),
        ),
    ]
