# Generated by Django 5.1.15 on 2026-08-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_remove_payrollrun_payroll_run_one_finalized_per_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollconfiguration',
            name='overtime_is_contribution_bearing',
            field=models.BooleanField(default=True, verbose_name='Overtime Is Contribution-Bearing'),
        ),
        migrations.AddField(
            model_name='payrollconfiguration',
            name='overtime_is_taxable',
            field=models.BooleanField(default=True, verbose_name='Overtime Is Taxable'),
        ),
        migrations.AddField(
            model_name='payrollconfiguration',
            name='standby_is_contribution_bearing',
            field=models.BooleanField(default=True, verbose_name='Standby Is Contribution-Bearing'),
        ),
        migrations.AddField(
            model_name='payrollconfiguration',
            name='standby_is_taxable',
            field=models.BooleanField(default=True, verbose_name='Standby Is Taxable'),
        ),
    ]
