# Generated by Django 5.1.15 on 2026-08-07 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payrollconfiguration_overtime_is_contribution_bearing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wageassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'effective_from'), name='wage_assignment_unique_active_start_per_user'),
        ),
    ]
