# Generated by Django 5.1.15 on 2026-08-08 08:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def copy_standby_rate_to_dual_fields(apps, schema_editor):
    """Copy the old single standby rate to both new weekday/weekend fields."""
    PayrollConfiguration = apps.get_model('payroll', 'PayrollConfiguration')
    for config in PayrollConfiguration.objects.all():
        old_rate = config.default_standby_hourly_rate
        config.weekday_standby_hourly_rate = old_rate
        config.weekend_standby_hourly_rate = old_rate
        config.save(update_fields=['weekday_standby_hourly_rate', 'weekend_standby_hourly_rate'])


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_wage_overlap_constraint'),
    ]

    operations = [
        # Step 1: Add new fields (with default=0, will be updated by data migration)
        migrations.AddField(
            model_name='payrollconfiguration',
            name='weekday_standby_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Lek per hour for standby on weekdays (Mon–Fri).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Weekday Standby Hourly Rate'),
        ),
        migrations.AddField(
            model_name='payrollconfiguration',
            name='weekend_standby_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Lek per hour for standby on weekends (Sat–Sun). Holidays use the weekday rate.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Weekend Standby Hourly Rate'),
        ),
        # Step 2: Copy old rate value to both new fields
        migrations.RunPython(
            copy_standby_rate_to_dual_fields,
            migrations.RunPython.noop,
        ),
        # Step 3: Remove the old field
        migrations.RemoveField(
            model_name='payrollconfiguration',
            name='default_standby_hourly_rate',
        ),
    ]
