# Generated by Django 5.1.15 on 2026-08-08 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_dual_standby_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollconfiguration',
            name='rounding_precision',
            field=models.PositiveSmallIntegerField(default=0, help_text='Decimal places for final amounts. 0 = whole Lek. Max 4.', validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Rounding Precision'),
        ),
    ]
