# Generated by Django 5.2.4 on 2026-08-09 11:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_rounding_precision_max_validator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollline',
            name='carryover_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Regular and carried overtime/standby source-period details.', verbose_name='Carryover Breakdown'),
        ),
        migrations.CreateModel(
            name='PayrollRunEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_kind', models.CharField(choices=[('overtime', 'Overtime'), ('standby', 'Standby')], max_length=20)),
                ('source_id', models.PositiveBigIntegerField()),
                ('work_date', models.DateField()),
                ('requested_period', models.DateField()),
                ('resolved_period', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('standby_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('source_status', models.CharField(default='approved', max_length=20)),
                ('resolution_reason', models.CharField(default='normal', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('reversed', 'Reversed')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_entries', to='payroll.payrollline')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_entries', to='payroll.payrollrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Run Entry',
                'verbose_name_plural': 'Payroll Run Entries',
                'ordering': ['run', 'user__username', 'work_date', 'source_kind', 'source_id'],
                'indexes': [models.Index(fields=['source_kind', 'source_id', 'status'], name='payroll_pay_source__4f78f5_idx'), models.Index(fields=['run', 'status'], name='payroll_pay_run_id_9be6a5_idx'), models.Index(fields=['user', 'resolved_period'], name='payroll_pay_user_id_b44f05_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'source_kind', 'source_id'), name='payroll_run_source_entry_unique'), models.UniqueConstraint(condition=models.Q(('status', 'finalized')), fields=('source_kind', 'source_id'), name='payroll_finalized_source_unique')],
            },
        ),
    ]
