# Generated by Django 5.2.4 on 2026-08-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_payrollconfiguration_require_tl_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollcontributionrate',
            name='cap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum monthly contribution base (Lek). Applied per month, not annualized. Null = no cap.', max_digits=12, null=True, verbose_name='Cap'),
        ),
        migrations.AlterField(
            model_name='payrollcontributionrate',
            name='floor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum monthly contribution base (Lek). Null = no floor.', max_digits=12, null=True, verbose_name='Floor'),
        ),
    ]
