# Generated by Django 5.2.4 on 2026-08-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_alter_payrollcontributionrate_cap_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payrollruleset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('country', 'tax_profile', 'effective_from'), name='payroll_ruleset_unique_active_effective_date'),
        ),
    ]
