# Generated by Django 5.2.4 on 2026-08-20 09:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='skills_skil_is_acti_d51391_idx')],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('target_level', models.PositiveSmallIntegerField(blank=True, help_text='Optional role-expectation level (1-5) for gap reporting.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='skills.skillcategory')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(help_text='Proficiency level (1=Foundational, 5=Mastery).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills_updated', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='skills.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Skill',
                'verbose_name_plural': 'User Skills',
                'ordering': ['-last_updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillRatingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('new_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_rating_changes', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_history', to='skills.skill')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_rating_history', to=settings.AUTH_USER_MODEL)),
                ('user_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='skills.userskill')),
            ],
            options={
                'verbose_name': 'Skill Rating History',
                'verbose_name_plural': 'Skill Rating History',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category', 'is_active', 'display_order'], name='skills_skil_categor_f78adb_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['is_active'], name='skills_skil_is_acti_a22cb2_idx'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='skill_category_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('code',), name='skill_code_unique'),
        ),
        migrations.AddIndex(
            model_name='userskill',
            index=models.Index(fields=['user', 'skill'], name='skills_user_user_id_acbe27_idx'),
        ),
        migrations.AddIndex(
            model_name='userskill',
            index=models.Index(fields=['skill', 'level'], name='skills_user_skill_i_130f6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='userskill',
            constraint=models.UniqueConstraint(fields=('user', 'skill'), name='user_skill_unique'),
        ),
        migrations.AddIndex(
            model_name='skillratinghistory',
            index=models.Index(fields=['user_skill', 'changed_at'], name='skills_skil_user_sk_1a9768_idx'),
        ),
        migrations.AddIndex(
            model_name='skillratinghistory',
            index=models.Index(fields=['user_id', 'changed_at'], name='skills_skil_user_id_2e446a_idx'),
        ),
        migrations.AddIndex(
            model_name='skillratinghistory',
            index=models.Index(fields=['skill_id', 'changed_at'], name='skills_skil_skill_i_2798ed_idx'),
        ),
    ]
