# Generated by Django 5.2.4 on 2026-08-21 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_seed_plugin_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillratinghistory',
            name='user_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='skills.userskill'),
        ),
    ]
