# Generated by Django 5.2.17 on 2026-08-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_skillratinghistory_user_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'ordering': ['name'], 'verbose_name': 'Skill Category', 'verbose_name_plural': 'Skill Categories'},
        ),
        migrations.RemoveIndex(
            model_name='skill',
            name='skills_skil_categor_f78adb_idx',
        ),
        migrations.RemoveIndex(
            model_name='skillcategory',
            name='skills_skil_is_acti_d51391_idx',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='target_level',
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category', 'is_active', 'name'], name='skills_skil_categor_cd0429_idx'),
        ),
        migrations.AddIndex(
            model_name='skillcategory',
            index=models.Index(fields=['is_active', 'name'], name='skills_skil_is_acti_3f08ce_idx'),
        ),
    ]
