# Generated by Django 5.2.17 on 2026-08-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_remove_skill_target_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='display_order',
        ),
    ]
