# Generated by Django 5.2.17 on 2026-09-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_remove_skill_display_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLevelLabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_1_label', models.CharField(default='Foundational', max_length=40)),
                ('level_2_label', models.CharField(default='Developing', max_length=40)),
                ('level_3_label', models.CharField(default='Proficient', max_length=40)),
                ('level_4_label', models.CharField(default='Advanced', max_length=40)),
                ('level_5_label', models.CharField(default='Mastery', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill Level Labels',
                'verbose_name_plural': 'Skill Level Labels',
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='skill_level_labels_singleton')],
            },
        ),
    ]
