# Generated by Django 5.2.17 on 2026-09-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_skilllevellabels'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_certifiable',
            field=models.BooleanField(default=False, help_text='Whether reaching mastery on this skill counts as a certification (TL KPI tracking).'),
        ),
        migrations.AddField(
            model_name='userskill',
            name='certified_on',
            field=models.DateField(blank=True, help_text='Set when this rating represents an achieved certification (TL KPI tracking).', null=True),
        ),
    ]
