# Generated by Django 5.2.17 on 2026-09-21 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0017_techlevel_drop_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TLApprovalMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('month', models.DateField(db_index=True, help_text='First day of the month')),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('team_size', models.PositiveIntegerField(default=0)),
                ('active_submitters', models.PositiveIntegerField(default=0)),
                ('approval_rate_pct', models.FloatField(blank=True, null=True)),
                ('resubmission_count', models.PositiveIntegerField(default=0)),
                ('engagement_score', models.FloatField(blank=True, null=True)),
                ('score_speed', models.FloatField(blank=True, null=True)),
                ('score_approval_rate', models.FloatField(blank=True, null=True)),
                ('score_activity', models.FloatField(blank=True, null=True)),
                ('score_consistency', models.FloatField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to='users.team')),
            ],
            options={
                'db_table': 'engagement_tl_approval_metrics',
                'ordering': ['-month', 'leader_id', 'team_id'],
                'indexes': [models.Index(fields=['leader', 'month'], name='engagement__leader__41f3b9_idx'), models.Index(fields=['team', 'month'], name='engagement__team_id_b9d14d_idx')],
                'constraints': [models.UniqueConstraint(fields=('leader', 'team', 'month'), name='unique_tl_team_month')],
            },
        ),
    ]
