# Generated by Django 5.2.17 on 2026-09-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlapprovalmetric',
            name='decisions_during_leave',
            field=models.PositiveIntegerField(default=0, help_text='Team-member requests this leader decided while on their own approved leave.'),
        ),
    ]
