# Generated by Django 6.0.4 on 2026-05-02 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_tl_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='user_profil_is_ital_f582cd_idx',
            old_name='user_profil_is_ital_8f7a2e_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='user_profil_is_alba_d86f98_idx',
            old_name='user_profil_is_alba_9c3b1f_idx',
        ),
        migrations.AddField(
            model_name='team',
            name='calendar_group',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Teams with the same calendar_group share calendar visibility', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hire_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date of hire for vacation accrual calculation', null=True),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['hire_date'], name='user_profil_hire_da_87bd6f_idx'),
        ),
    ]
