# Generated by Django 5.1.15 on 2026-05-04 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_profil_is_ital_8f7a2e_idx_user_profil_is_ital_f582cd_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='user_profil_is_ital_f582cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='user_profil_is_alba_d86f98_idx',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_albanian_tl',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_italian_tl',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='albanian_tl',
            field=models.ForeignKey(blank=True, help_text='Albanian Team Leader assigned to this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albanian_team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='italian_tl',
            field=models.ForeignKey(blank=True, help_text='Italian Team Leader assigned to this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='italian_team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['albanian_tl'], name='user_profil_albania_6a2800_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['italian_tl'], name='user_profil_italian_69e953_idx'),
        ),
    ]
