# Generated by Django 5.1.15 on 2026-05-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprofile_user_profil_is_ital_f582cd_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='employee_id',
        ),
    ]
