# Generated by Django 5.1.15 on 2026-05-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_albanian_tl_role',
            field=models.BooleanField(db_index=True, default=False, help_text='Explicitly marks user as an Albanian Team Leader (role-based)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_italian_tl_role',
            field=models.BooleanField(db_index=True, default=False, help_text='Explicitly marks user as an Italian Team Leader (role-based)'),
        ),
    ]
