# Generated by Django 5.1.15 on 2026-05-09 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_is_albanian_tl_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='user_profil_is_hr_ab4743_idx',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_hr',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_hr_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hire_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date of hire for leave accrual calculation', null=True),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_hr_user'], name='user_profil_is_hr_u_d64668_idx'),
        ),
    ]
