# Generated by Django 5.1.15 on 2026-05-11 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_userprofile_user_profil_is_hr_ab4743_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('joined_date', models.DateField(blank=True, help_text='Date when user joined this team', null=True)),
                ('is_primary_team', models.BooleanField(default=False, help_text='Mark this as the user primary team for calendar default')),
            ],
            options={
                'db_table': 'team_memberships',
            },
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='user_profil_team_id_aa5067_idx',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='team',
        ),
        migrations.AddField(
            model_name='teammembership',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='users.team'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='members', through='users.TeamMembership', to='users.team'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['user_profile', 'is_primary_team'], name='team_member_user_pr_211645_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['team'], name='team_member_team_id_198236_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together={('user_profile', 'team')},
        ),
    ]
