# Generated by Django 5.2.4 on 2026-07-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0003_overtimelog_overtime_lo_client__aac471_idx_and_more'),
        ('users', '0009_restore_team_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='clients',
            field=models.ManyToManyField(blank=True, help_text='Clients this user is assigned to (used for KPI evidence and uploads)', related_name='assigned_users', to='overtime.client'),
        ),
    ]
