# Generated by Django 5.1.15 on 2026-08-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userprofile_role_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role_codes',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
    ]
