# Generated by Django 5.2.4 on 2026-08-09 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_userprofile_role_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalPeriodBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('period', models.DateField(db_index=True, unique=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approval_period_boundaries',
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalPeriodClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(db_index=True)),
                ('scope_type', models.CharField(default='managed_scope', max_length=40)),
                ('scope_key', models.CharField(max_length=100)),
                ('boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closes', to='users.approvalperiodboundary')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_period_closes', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approval_period_closes',
                'ordering': ['-closed_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalPeriodCloseMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('close', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users.approvalperiodclose')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('source_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_period_close_members', to='users.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_period_close_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approval_period_close_members',
            },
        ),
        migrations.AddIndex(
            model_name='approvalperiodclose',
            index=models.Index(fields=['boundary', 'closed_at'], name='approval_pe_boundar_d24cf7_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalperiodclose',
            index=models.Index(fields=['closed_by', 'boundary'], name='approval_pe_closed__6abd10_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalperiodclose',
            constraint=models.UniqueConstraint(fields=('boundary', 'scope_key'), name='approval_close_boundary_scope_unique'),
        ),
        migrations.AddIndex(
            model_name='approvalperiodclosemember',
            index=models.Index(fields=['user', 'close'], name='approval_pe_user_id_34332c_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalperiodclosemember',
            constraint=models.UniqueConstraint(fields=('close', 'user'), name='approval_close_member_unique'),
        ),
    ]
