# Generated by Django 5.2.17 on 2026-09-13 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_techlevel_and_usertech_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techlevel',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='techlevel',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='techlevel',
            name='is_deleted',
        ),
    ]
