# Generated by Django 5.2.17 on 2026-09-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_techlevel_drop_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='seniority_level',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior')], help_text='Used for the junior/senior workforce-ratio KPI.', max_length=10, null=True),
        ),
    ]
