# Generated by Django 5.2.17 on 2026-10-01 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_userprofile_seniority_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HbprAlbanianTlAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cadence', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('albanian_tl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hbpr_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hbpr_assignments_granted', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hbpr_assignments_ended', to=settings.AUTH_USER_MODEL)),
                ('hbpr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hbpr_albanian_tl_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hbpr_albanian_tl_assignments',
                'ordering': ['-effective_from', '-id'],
                'indexes': [models.Index(fields=['hbpr', 'effective_from', 'effective_to'], name='hbpr_assign_hbpr_range_idx'), models.Index(fields=['albanian_tl', 'effective_to'], name='hbpr_assign_tl_end_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='hbpr_assignment_end_not_before_start'), models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('albanian_tl',), name='unique_open_hbpr_assignment_per_al_tl')],
            },
        ),
    ]
