"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from core.plugins.registry import plugin_registry

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(parents=True, exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# This is the DEVELOPMENT settings module (used by manage.py / wsgi / asgi).
# Production uses config.settings_production, which forces DEBUG=False and
# enforces SECRET_KEY / ALLOWED_HOSTS / FRONTEND_URL guards. Here we default
# to DEBUG=True so `python manage.py runserver` works without env vars; both
# DEBUG and SECRET_KEY remain overridable via environment variables.
DEBUG = os.getenv('DEBUG', '1').strip().lower() in {'1', 'true', 'yes', 'on'}

# SECURITY WARNING: keep the secret key used in production secret!
_INSECURE_DEV_KEY = 'django-insecure-#h&uhd_1pp-56h5&yl%f(3o($x5!-9v1dt4ov5@+alf+m7x+d)'
SECRET_KEY = os.getenv('SECRET_KEY', _INSECURE_DEV_KEY)

# ALLOWED_HOSTS: read from env var (comma-separated) or use safe dev defaults.
_allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '')
if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_extensions',
    'drf_spectacular',
    'django_filters',
    # Local apps
    'apps.users',
    'apps.overtime',
    'apps.standby',
    'apps.leave_management',
    'apps.permissions',
    'apps.reports',
    'apps.dashboard',
    'apps.plugins',
]

# Load Plugin Apps
INSTALLED_APPS += plugin_registry.get_plugin_apps()

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.user_context.UserContextMiddleware',
    'core.plugins.middleware.PluginTableErrorMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# --- Test performance optimizations ---
# Detect test runs via the test runner's manage.py test command.
# These settings make test runs 3-5x faster with zero impact on dev/prod.
import sys as _sys  # noqa: E402  (mid-file: detect test runs before DATABASES override)
_IS_TESTING = 'test' in _sys.argv or ('pytest' in _sys.argv[0] if _sys.argv else False)

if _IS_TESTING:
    # Use fast password hasher (PBKDF2 does ~100k iterations by default;
    # MD5 does 1 iteration). Only safe in tests — never in production.
    PASSWORD_HASHERS = [
        'django.contrib.auth.hashers.MD5PasswordHasher',
    ]

    # Use in-memory SQLite for faster I/O (no disk writes during tests)
    DATABASES['default']['TEST'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }

    # Reduce log noise during tests
    LOGGING_CONFIG = None


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (user uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
        # Scoped rates — apply via `throttle_scope = "..."` on a ViewSet/action.
        # Disabled in dev/test to avoid 429s in the test suite; set real limits
        # when the production settings profile is built.
        'auth': '20/min' if not DEBUG else None,          # login/token refresh
        'upload': '30/hour' if not DEBUG else None,       # file parsing endpoints
        'export': '20/hour' if not DEBUG else None,       # report/export endpoints
        'evidence_upload': '60/hour' if not DEBUG else None,
        'control_room': '120/hour' if not DEBUG else None,  # dashboard summary/trend/roster reads
        'health': '60/min' if not DEBUG else None,  # P2-11: readiness probe throttle
    }
}

# Simple JWT configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
}

# CORS configuration
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:5174',
    'http://127.0.0.1:5174',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]

CORS_ALLOW_CREDENTIALS = True

# Extend the default allowed headers to include Idempotency-Key, which is
# sent by the offline queue flush and the IdempotentCreateMixin. Without
# this, CORS preflight blocks cross-origin POSTs that include the header.
from corsheaders.defaults import default_headers  # noqa: E402

CORS_ALLOW_HEADERS = list(default_headers) + ['Idempotency-Key']

# DRF Spectacular configuration
SPECTACULAR_SETTINGS = {
    'TITLE': 'Time Tracker API',
    'DESCRIPTION': 'API for Time Tracker application with overtime, standby, and leave management',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'ENUM_NAME_OVERRIDES': {
        'RequestStatusEnum': 'apps.leave_management.models.core.LeaveRequest.STATUS_CHOICES',
        'ApprovalStatusEnum': 'apps.overtime.models.core.OvertimeLog.STATUS_CHOICES',
        'ReportStatusEnum': 'apps.reports.models.core.GeneratedReport.STATUS_CHOICES',
        'CoreAuditActionEnum': 'apps.reports.models.core.AuditLog.ACTION_CHOICES',
        'PluginAuditActionEnum': 'plugins.audit_log.models.AuditLog.ACTION_TYPES',
        'PluginAuditStatusEnum': [
            ('success', 'Success'),
            ('failure', 'Failure'),
            ('pending', 'Pending'),
        ],
        'PluginPermissionActionEnum': 'apps.plugins.models.PluginPermission.ACTION_CHOICES',
        'SnapshotFrequencyEnum': 'plugins.analytics.models.AnalyticsSnapshot.SNAPSHOT_TYPES',
        # evidence_type is defined on both OvertimeLog and KPIEvidence with
        # different choice sets; give each a distinct generated enum name.
        'OvertimeEvidenceTypeEnum': 'apps.overtime.models.core.OvertimeLog.EVIDENCE_TYPE_CHOICES',
        'KPIEvidenceTypeEnum': 'plugins.ticket_kpi.models.KPIEvidence.EVIDENCE_TYPES',
    },
}

# Crispy Forms configuration
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Cache configuration - Use LocMemCache for development, Redis for production
if os.getenv('USE_REDIS', 'false').lower() == 'true':
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
                'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
                'IGNORE_EXCEPTIONS': True,
                'MAX_ENTRIES': 10000,
                'CULL_FREQUENCY': 3,
            }
        }
    }
else:
    # Development: Use LocMemCache (no external dependencies)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'engineering-tracker-cache',
            'OPTIONS': {
                'MAX_ENTRIES': 10000,
            }
        }
    }

# Cache versioning - increment on deployment to invalidate all cache
CACHE_VERSION = int(os.getenv('CACHE_VERSION', '1'))

# Standardized cache timeout settings (in seconds)
CACHE_TIMEOUT = {
    'REAL_TIME': 0,           # No cache
    'SHORT': 60,              # 1 minute (dashboard, live counts)
    'MEDIUM': 300,            # 5 minutes (balances, team data)
    'LONG': 1800,             # 30 minutes (permissions, roles)
    'VERY_LONG': 86400,       # 24 hours (settings, holidays)
}

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'apps': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}
