# Generated by Django 5.2.4 on 2026-05-31 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_restore_team_memberships'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20, verbose_name='Snapshot Type')),
                ('snapshot_date', models.DateField(db_index=True, verbose_name='Snapshot Date')),
                ('leave_approved_count', models.IntegerField(default=0, verbose_name='Approved Leave Requests')),
                ('leave_pending_count', models.IntegerField(default=0, verbose_name='Pending Leave Requests')),
                ('leave_rejected_count', models.IntegerField(default=0, verbose_name='Rejected Leave Requests')),
                ('leave_total_days', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Leave Days')),
                ('overtime_approved_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Approved Overtime Hours')),
                ('overtime_pending_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pending Overtime Hours')),
                ('overtime_total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Overtime Cost')),
                ('standby_scheduled_count', models.IntegerField(default=0, verbose_name='Scheduled Standby')),
                ('standby_completed_count', models.IntegerField(default=0, verbose_name='Completed Standby')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analytics Snapshot',
                'verbose_name_plural': 'Analytics Snapshots',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['snapshot_type', '-snapshot_date'], name='analytics_a_snapsho_80706d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('leave_approval_rate', 'Leave Approval Rate'), ('overtime_cost_trend', 'Overtime Cost Trend'), ('team_performance', 'Team Performance'), ('user_balance', 'User Balance')], db_index=True, max_length=50, verbose_name='Metric Type')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Value')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Label')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Recorded At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_metrics', to='users.team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytics Metric',
                'verbose_name_plural': 'Analytics Metrics',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['metric_type', '-recorded_at'], name='analytics_a_metric__e63149_idx'), models.Index(fields=['user', '-recorded_at'], name='analytics_a_user_id_da38d3_idx'), models.Index(fields=['team', '-recorded_at'], name='analytics_a_team_id_a64cc4_idx')],
            },
        ),
    ]
