# Generated by Django 5.1.15 on 2026-06-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20, verbose_name='Snapshot Frequency')),
                ('data_retention_days', models.IntegerField(default=365, help_text='Number of days to keep historical analytics data', verbose_name='Data Retention Days')),
                ('enabled_metrics', models.JSONField(blank=True, default=list, help_text='List of metric types to track', verbose_name='Enabled Metrics')),
                ('auto_snapshot_enabled', models.BooleanField(default=True, help_text='Whether to automatically generate snapshots', verbose_name='Auto Snapshot Enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analytics Configuration',
                'verbose_name_plural': 'Analytics Configurations',
            },
        ),
    ]
