# Generated by Django 5.1.15 on 2026-06-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_analyticsconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticssnapshot',
            name='active_users',
            field=models.IntegerField(default=0, verbose_name='Active Users'),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='average_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Average Hours'),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Hours'),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='total_users',
            field=models.IntegerField(default=0, verbose_name='Total Users'),
        ),
    ]
