# Generated by Django 5.1.15 on 2026-06-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_analyticssnapshot_active_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDailyBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('leave_days', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overtime_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('standby_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('team_data', models.JSONField(blank=True, default=dict)),
                ('client_data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analytics Daily Bucket',
                'verbose_name_plural': 'Analytics Daily Buckets',
                'ordering': ['-date'],
            },
        ),
    ]
