# Generated by Django 5.1.15 on 2026-06-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_analyticsdailybucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsconfiguration',
            name='alert_recipients',
            field=models.JSONField(blank=True, default=list, help_text='User IDs to notify when thresholds are exceeded', verbose_name='Alert Recipients'),
        ),
        migrations.AddField(
            model_name='analyticsconfiguration',
            name='enable_threshold_alerts',
            field=models.BooleanField(default=False, help_text='Send alerts when metrics exceed thresholds', verbose_name='Enable Threshold Alerts'),
        ),
        migrations.AddField(
            model_name='analyticsconfiguration',
            name='mtta_threshold_hours',
            field=models.FloatField(default=48, help_text='Mean Time to Approval threshold before alerting', verbose_name='MTTA Threshold (Hours)'),
        ),
        migrations.AddField(
            model_name='analyticsconfiguration',
            name='overtime_cost_threshold',
            field=models.DecimalField(decimal_places=2, default=5000, help_text='Monthly budget threshold for overtime cost', max_digits=15, verbose_name='Overtime Cost Threshold (€)'),
        ),
    ]
