# Generated by Django 5.1.15 on 2026-06-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_analyticsconfiguration_alert_recipients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Template Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('layout_config', models.JSONField(default=dict, help_text='JSON defining the report layout', verbose_name='Layout Config')),
                ('column_selection', models.JSONField(default=list, help_text='List of columns to include', verbose_name='Column Selection')),
                ('chart_config', models.JSONField(blank=True, default=dict, help_text='Configuration for embedded charts', verbose_name='Chart Config')),
                ('branding_config', models.JSONField(blank=True, default=dict, help_text='Custom logos, colors, and headers', verbose_name='Branding Config')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Report Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('schedule_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20, verbose_name='Schedule Type')),
                ('recipients', models.JSONField(default=list, help_text='List of email addresses', verbose_name='Recipients')),
                ('filter_preset', models.JSONField(blank=True, default=dict, help_text='JSON representation of filter parameters', verbose_name='Filter Preset')),
                ('report_format', models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF'), ('csv', 'CSV')], default='excel', max_length=10, verbose_name='Format')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Run')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Next Run')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scheduled Report',
                'verbose_name_plural': 'Scheduled Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
