# Generated by Django 5.1.15 on 2026-08-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_reporttemplate_scheduledreport'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='analyticsconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('pk', 1)), name='analytics_configuration_singleton'),
        ),
        migrations.AddConstraint(
            model_name='analyticssnapshot',
            constraint=models.UniqueConstraint(fields=('snapshot_type', 'snapshot_date'), name='analytics_snapshot_type_date_unique'),
        ),
        migrations.AddConstraint(
            model_name='reporttemplate',
            constraint=models.UniqueConstraint(fields=('name',), name='analytics_report_template_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='scheduledreport',
            constraint=models.UniqueConstraint(fields=('name',), name='scheduled_report_name_unique'),
        ),
    ]
