# Generated by Django 5.1.15 on 2026-08-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_analyticsconfiguration_analytics_configuration_singleton_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticsconfiguration',
            name='overtime_cost_threshold',
        ),
        migrations.RemoveField(
            model_name='analyticsdailybucket',
            name='overtime_cost',
        ),
        migrations.RemoveField(
            model_name='analyticssnapshot',
            name='overtime_total_cost',
        ),
        migrations.AlterField(
            model_name='analyticsmetric',
            name='metric_type',
            field=models.CharField(choices=[('leave_approval_rate', 'Leave Approval Rate'), ('team_performance', 'Team Performance'), ('user_balance', 'User Balance')], db_index=True, max_length=50, verbose_name='Metric Type'),
        ),
    ]
