# Generated by Django 5.1.15 on 2026-08-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_remove_analyticsconfiguration_overtime_cost_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsconfiguration',
            name='backlog_threshold',
            field=models.IntegerField(default=5, help_text='Minimum pending items to trigger backlog alert. Default: 5', verbose_name='Backlog Threshold'),
        ),
        migrations.AddField(
            model_name='analyticsconfiguration',
            name='concentration_threshold',
            field=models.FloatField(default=0.4, help_text='Minimum share (0-1) by one user to trigger concentration alert. Default: 0.40 (40%)', verbose_name='Concentration Threshold'),
        ),
        migrations.AddField(
            model_name='analyticsconfiguration',
            name='spike_threshold',
            field=models.FloatField(default=2.0, help_text='Multiplier of daily average to trigger spike insight. Default: 2.0 (2x)', verbose_name='Spike Threshold'),
        ),
        migrations.AddField(
            model_name='analyticsconfiguration',
            name='status_bottleneck_threshold',
            field=models.FloatField(default=0.3, help_text='Minimum pending ratio (0-1) to trigger bottleneck alert. Default: 0.30 (30%)', verbose_name='Status Bottleneck Threshold'),
        ),
        migrations.AddField(
            model_name='analyticsconfiguration',
            name='trend_threshold',
            field=models.FloatField(default=0.15, help_text='Minimum percentage change (0-1) to trigger a trend insight. Default: 0.15 (15%)', verbose_name='Trend Threshold'),
        ),
    ]
