# Generated by Django 5.1.15 on 2026-08-07 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_add_insight_thresholds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('report_format', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV')], default='excel', max_length=10, verbose_name='Format')),
                ('filter_params', models.JSONField(default=dict, verbose_name='Filter Parameters')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='File Path')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('file_size_bytes', models.BigIntegerField(default=0, verbose_name='File Size')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export Job',
                'verbose_name_plural': 'Export Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='analytics_e_status_c9c0a2_idx'), models.Index(fields=['created_by', '-created_at'], name='analytics_e_created_46c026_idx')],
            },
        ),
    ]
