# Generated by Django 5.2.4 on 2026-05-01 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandbyPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('pattern_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('weekend', 'Weekend'), ('custom', 'Custom')], max_length=20)),
                ('day_of_week', models.IntegerField(blank=True, help_text='For weekly pattern: 0=Monday, 6=Sunday', null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standby_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'standby_patterns',
                'ordering': ['user', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StandbyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_weekend', models.BooleanField(default=False)),
                ('is_holiday', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('calculated_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_standby', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standby_logs', to=settings.AUTH_USER_MODEL)),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='standby.standbypattern')),
            ],
            options={
                'db_table': 'standby_logs',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='standbypattern',
            index=models.Index(fields=['user'], name='standby_pat_user_id_c8f2c5_idx'),
        ),
        migrations.AddIndex(
            model_name='standbypattern',
            index=models.Index(fields=['pattern_type'], name='standby_pat_pattern_2c737d_idx'),
        ),
        migrations.AddIndex(
            model_name='standbypattern',
            index=models.Index(fields=['is_active'], name='standby_pat_is_acti_82d8ec_idx'),
        ),
        migrations.AddIndex(
            model_name='standbylog',
            index=models.Index(fields=['user', 'date'], name='standby_log_user_id_44eab2_idx'),
        ),
        migrations.AddIndex(
            model_name='standbylog',
            index=models.Index(fields=['status'], name='standby_log_status_fccd69_idx'),
        ),
        migrations.AddIndex(
            model_name='standbylog',
            index=models.Index(fields=['is_weekend'], name='standby_log_is_week_8fa7a8_idx'),
        ),
        migrations.AddIndex(
            model_name='standbylog',
            index=models.Index(fields=['is_holiday'], name='standby_log_is_holi_d6d9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='standbylog',
            index=models.Index(fields=['date'], name='standby_log_date_5e9dac_idx'),
        ),
        migrations.AddConstraint(
            model_name='standbylog',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_standby_per_day'),
        ),
    ]
