# Generated by Django 5.1.15 on 2026-05-09 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standby', '0002_add_time_fields_remove_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='standbypattern',
            name='standby_pat_pattern_2c737d_idx',
        ),
        migrations.RemoveField(
            model_name='standbypattern',
            name='pattern_type',
        ),
        migrations.AddField(
            model_name='standbypattern',
            name='recurrence_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('weekend', 'Weekend'), ('custom', 'Custom')], default='weekly', max_length=20),
        ),
        migrations.AddIndex(
            model_name='standbypattern',
            index=models.Index(fields=['recurrence_type'], name='standby_pat_recurre_e68522_idx'),
        ),
    ]
