# Generated by Django 5.1.15 on 2026-06-04 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standby', '0003_remove_standbypattern_standby_pat_pattern_2c737d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standbypattern',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='standbypattern',
            name='user',
        ),
        migrations.RemoveField(
            model_name='standbylog',
            name='pattern',
        ),
        migrations.RemoveConstraint(
            model_name='standbylog',
            name='unique_standby_per_day',
        ),
        migrations.RemoveIndex(
            model_name='standbylog',
            name='standby_log_status_fccd69_idx',
        ),
        migrations.RemoveField(
            model_name='standbylog',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='standbylog',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='standbylog',
            name='calculated_wage',
        ),
        migrations.RemoveField(
            model_name='standbylog',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='standbylog',
            name='evidence',
        ),
        migrations.RemoveField(
            model_name='standbylog',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='standbylog',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='standbylog',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AddIndex(
            model_name='standbylog',
            index=models.Index(fields=['status', 'date'], name='standby_log_status_f15d79_idx'),
        ),
        migrations.AddIndex(
            model_name='standbylog',
            index=models.Index(fields=['user', 'status', 'date'], name='standby_log_user_id_bfb8cf_idx'),
        ),
        migrations.DeleteModel(
            name='StandbyPattern',
        ),
    ]
