# Generated by Django 5.1.15 on 2026-06-04 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standby', '0004_remove_standbypattern_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandbyPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('recurrence_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('weekend', 'Weekend'), ('custom', 'Custom')], default='weekly', max_length=20)),
                ('day_of_week', models.IntegerField(blank=True, help_text='For weekly pattern: 0=Monday, 6=Sunday', null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'standby_patterns',
                'ordering': ['user', 'name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='standbylog',
            name='standby_log_status_f15d79_idx',
        ),
        migrations.AddField(
            model_name='standbylog',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standbylog',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_standby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='standbylog',
            name='calculated_wage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='standbylog',
            name='end_time',
            field=models.TimeField(blank=True, help_text='End time in 24h format', null=True),
        ),
        migrations.AddField(
            model_name='standbylog',
            name='evidence',
            field=models.TextField(blank=True, help_text='Ticket numbers, call references, etc.'),
        ),
        migrations.AddField(
            model_name='standbylog',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='standbylog',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Start time in 24h format', null=True),
        ),
        migrations.AlterField(
            model_name='standbylog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='standbypattern',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_standby_patterns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='standbypattern',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standby_patterns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='standbylog',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='standby.standbypattern'),
        ),
        migrations.AddIndex(
            model_name='standbylog',
            index=models.Index(fields=['status'], name='standby_log_status_fccd69_idx'),
        ),
        migrations.AddConstraint(
            model_name='standbylog',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_standby_per_day'),
        ),
        migrations.AddIndex(
            model_name='standbypattern',
            index=models.Index(fields=['user'], name='standby_pat_user_id_c8f2c5_idx'),
        ),
        migrations.AddIndex(
            model_name='standbypattern',
            index=models.Index(fields=['recurrence_type'], name='standby_pat_recurre_e68522_idx'),
        ),
        migrations.AddIndex(
            model_name='standbypattern',
            index=models.Index(fields=['is_active'], name='standby_pat_is_acti_82d8ec_idx'),
        ),
    ]
