# Generated by Django 5.1.15 on 2026-08-05 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standby', '0005_standbypattern_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='standbylog',
            name='calculated_wage',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='standbypattern',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='standby_pattern_user_name_unique'),
        ),
    ]
