# Generated by Django 5.1.15 on 2026-08-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standby', '0006_alter_standbylog_calculated_wage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standbylog',
            name='calculated_wage',
        ),
    ]
