# Generated by Django 5.2.4 on 2026-08-09 10:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_processing_fields(apps, schema_editor):
    StandbyLog = apps.get_model('standby', 'StandbyLog')
    rows = []
    for row in StandbyLog.objects.all().only('id', 'date', 'created_at'):
        row.submitted_at = row.created_at
        row.requested_processing_period = row.date.replace(day=1)
        rows.append(row)
    StandbyLog.objects.bulk_update(
        rows,
        ['submitted_at', 'requested_processing_period'],
        batch_size=1000,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('standby', '0007_remove_standbylog_calculated_wage'),
        ('users', '0013_approvalperiodboundary_approvalperiodclose_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='standbylog',
            name='approval_period_close',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standby_logs', to='users.approvalperiodclose'),
        ),
        migrations.AddField(
            model_name='standbylog',
            name='requested_processing_period',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='standbylog',
            name='resolved_settlement_period',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='standbylog',
            name='submitted_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddIndex(
            model_name='standbylog',
            index=models.Index(fields=['requested_processing_period', 'status'], name='standby_log_request_05c4f2_idx'),
        ),
        migrations.AddIndex(
            model_name='standbylog',
            index=models.Index(fields=['user', 'requested_processing_period'], name='standby_log_user_id_6015a2_idx'),
        ),
        migrations.RunPython(backfill_processing_fields, migrations.RunPython.noop),
    ]
