# Generated by Django 5.2.4 on 2026-08-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0007_remove_unique_overtime_per_day_client'),
        ('standby', '0008_standbylog_approval_period_close_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='standbylog',
            name='unique_standby_per_day',
        ),
        migrations.AddField(
            model_name='standbylog',
            name='clients',
            field=models.ManyToManyField(blank=True, help_text='Clients covered by this standby entry (multiple allowed).', related_name='standby_logs', to='overtime.client'),
        ),
    ]
