# Generated by Django 5.2.17 on 2026-09-25 08:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0017_techlevel_drop_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdleFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reference_url', models.URLField(blank=True, help_text='Link to evidence stored elsewhere.')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('flagged_on', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('productivity_task', models.TextField(blank=True)),
                ('resolved_on', models.DateField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idle_flags', to=settings.AUTH_USER_MODEL)),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idle_flags_raised', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tl_scorecard_idle_flags',
                'ordering': ['-flagged_on'],
            },
        ),
        migrations.CreateModel(
            name='IdleStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('week_of', models.DateField(help_text='Monday of the reported week.')),
                ('status_note', models.TextField(blank=True)),
                ('productivity_task_snapshot', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='tl_scorecard.idleflag')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tl_scorecard_idle_status_updates',
                'ordering': ['-week_of'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reference_url', models.URLField(blank=True, help_text='Link to evidence stored elsewhere.')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meeting_type', models.CharField(choices=[('one_on_one', 'One-on-one'), ('tl_sync', 'TL Sync'), ('team_meeting', 'Team Meeting')], max_length=20)),
                ('occurred_on', models.DateField()),
                ('notes_published_at', models.DateTimeField(blank=True, null=True)),
                ('counterparty', models.ForeignKey(blank=True, help_text='Single counterpart for one_on_one/tl_sync. Not used for team_meeting (see attendees).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_as_counterparty', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings_organized', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, help_text='Set for team_meeting; optional for one_on_one/tl_sync.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='users.team')),
            ],
            options={
                'db_table': 'tl_scorecard_meetings',
                'ordering': ['-occurred_on'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('member', 'Member'), ('hrbp', 'HRBP'), ('observer', 'Observer')], default='member', max_length=20)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='tl_scorecard.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tl_scorecard_meeting_attendees',
            },
        ),
        migrations.CreateModel(
            name='ReviewDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reference_url', models.URLField(blank=True, help_text='Link to evidence stored elsewhere.')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('period', models.CharField(help_text='YYYY-MM the review covers.', max_length=7)),
                ('recipient', models.CharField(max_length=255)),
                ('delivered_on', models.DateField()),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_deliveries', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tl_scorecard_review_deliveries',
                'ordering': ['-delivered_on'],
            },
        ),
        migrations.CreateModel(
            name='EngagementSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('period', models.CharField(help_text='YYYY-MM the response covers.', max_length=7)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_survey_responses', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_survey_responses', to='users.team')),
            ],
            options={
                'db_table': 'tl_scorecard_engagement_survey_responses',
                'ordering': ['-period'],
                'constraints': [models.UniqueConstraint(fields=('respondent', 'period'), name='unique_survey_response_per_period')],
            },
        ),
        migrations.AddIndex(
            model_name='idleflag',
            index=models.Index(fields=['employee', 'status'], name='tl_scorecar_employe_e06d4c_idx'),
        ),
        migrations.AddConstraint(
            model_name='idlestatusupdate',
            constraint=models.UniqueConstraint(fields=('flag', 'week_of'), name='unique_idle_status_per_week'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['organizer', 'meeting_type', 'occurred_on'], name='tl_scorecar_organiz_34e0d4_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['counterparty', 'occurred_on'], name='tl_scorecar_counter_4c2818_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingattendee',
            constraint=models.UniqueConstraint(fields=('meeting', 'user'), name='unique_meeting_attendee'),
        ),
        migrations.AddIndex(
            model_name='reviewdelivery',
            index=models.Index(fields=['leader', 'period'], name='tl_scorecar_leader__d09b3c_idx'),
        ),
    ]
