# Generated by Django 5.2.17 on 2026-09-25 09:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl_scorecard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EPRCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('year', models.PositiveIntegerField()),
                ('goal_setting_completed_at', models.DateTimeField(blank=True, null=True)),
                ('mid_year_completed_at', models.DateTimeField(blank=True, null=True)),
                ('final_review_completed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tl_scorecard_epr_cycles',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='EPRGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='tl_scorecard.eprcycle')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tl_scorecard_epr_goals',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PIPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reference_url', models.URLField(blank=True, help_text='Link to evidence stored elsewhere.')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('start_date', models.DateField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Set by an HR user when the PIP is approved. Null = pending approval.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pip_records_approved', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pip_records', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pip_records_managed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tl_scorecard_pip_records',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PromotionFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nominated_on', models.DateField()),
                ('status', models.CharField(choices=[('nominated', 'Nominated'), ('promoted', 'Promoted'), ('declined', 'Declined')], default='nominated', max_length=20)),
                ('decided_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_flags', to=settings.AUTH_USER_MODEL)),
                ('nominated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_flags_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tl_scorecard_promotion_flags',
                'ordering': ['-nominated_on'],
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reference_url', models.URLField(blank=True, help_text='Link to evidence stored elsewhere.')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('absence_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('addressed_on', models.DateField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL)),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences_flagged', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tl_scorecard_absences',
                'ordering': ['-absence_date'],
                'indexes': [models.Index(fields=['employee', 'absence_date'], name='tl_scorecar_employe_d3d071_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='eprcycle',
            constraint=models.UniqueConstraint(fields=('user', 'year'), name='unique_epr_cycle_per_user_year'),
        ),
        migrations.AddIndex(
            model_name='piprecord',
            index=models.Index(fields=['employee', 'status'], name='tl_scorecar_employe_965214_idx'),
        ),
    ]
