# Generated by Django 5.2.17 on 2026-10-01 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl_scorecard', '0002_eprcycle_eprgoal_piprecord_promotionflag_absence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='shared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='shared_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meetingattendee',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='piprecord',
            name='closed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piprecord',
            name='shared_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='piprecord',
            name='status_note',
            field=models.TextField(blank=True, help_text='Reason recorded when a PIP is returned, completed or cancelled.'),
        ),
        migrations.AddField(
            model_name='promotionflag',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_flags_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionflag',
            name='decision_note',
            field=models.TextField(blank=True),
        ),
    ]
