# Generated by Django 5.2.17 on 2026-10-01 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl_scorecard', '0003_meeting_shared_at_meeting_shared_summary_and_more'),
        ('users', '0019_hbpr_albanian_tl_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HbprGovernanceEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('cadence_meeting', 'Cadence meeting'), ('epr_mid_year', 'EPR mid-year participation'), ('epr_year_end', 'EPR year-end participation')], max_length=20)),
                ('occurred_on', models.DateField()),
                ('reporting_year', models.PositiveIntegerField(blank=True, null=True)),
                ('shared_summary', models.TextField(blank=True)),
                ('action_items', models.TextField(blank=True)),
                ('reference_url', models.URLField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='governance_evidence', to='users.hbpralbaniantlassignment')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hbpr_evidence_recorded', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hbpr_evidence_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tl_scorecard_hbpr_governance_evidence',
                'ordering': ['-occurred_on', '-id'],
                'indexes': [models.Index(fields=['assignment', 'kind', 'occurred_on'], name='hbpr_evidence_assign_kind_idx'), models.Index(fields=['reporting_year', 'kind'], name='hbpr_evidence_year_kind_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['epr_mid_year', 'epr_year_end']), ('reporting_year__isnull', False)), models.Q(('kind', 'cadence_meeting'), ('reporting_year__isnull', True)), _connector='OR'), name='hbpr_evidence_year_matches_kind'), models.UniqueConstraint(condition=models.Q(('kind__in', ['epr_mid_year', 'epr_year_end'])), fields=('assignment', 'kind', 'reporting_year'), name='unique_hbpr_epr_evidence_per_year')],
            },
        ),
    ]
