# Generated by Django 6.1.1 on 2026-10-04 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl_scorecard', '0004_hbpr_governance_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EPRStageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('goal_setting', 'Goal setting'), ('mid_year', 'Mid-year'), ('final_review', 'Final review')], max_length=20)),
                ('summary', models.TextField()),
                ('reference_url', models.URLField(blank=True, help_text='Link to the review artifact (e.g. Workday).')),
                ('shared_with_employee', models.BooleanField(default=False)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_records', to='tl_scorecard.eprcycle')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='epr_stage_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tl_scorecard_epr_stage_records',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('cycle', 'stage'), name='unique_epr_stage_record_per_cycle_stage')],
            },
        ),
    ]
