# Generated by Django 5.2.4 on 2026-07-26 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_userprofile_clients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlRoomAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive records deny dashboard access even if scopes exist.', verbose_name='Active')),
                ('display_name', models.CharField(blank=True, help_text='Optional dashboard label; defaults to the user full name.', max_length=120, verbose_name='Display Name')),
                ('timezone', models.CharField(blank=True, help_text='Optional future display timezone; defaults to application timezone.', max_length=64, verbose_name='Display Timezone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Administrator who granted this access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_room_access_granted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Administrator who last changed this access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_room_access_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='Existing application user granted Control Room access.', on_delete=django.db.models.deletion.CASCADE, related_name='control_room_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Control Room Access',
                'verbose_name_plural': 'Control Room Access',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='ControlRoomTeamScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_subteams', models.BooleanField(default=False, help_text='Reserved for future hierarchy expansion. MVP: always False.', verbose_name='Include Subteams')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access', models.ForeignKey(help_text='Control Room access record this scope belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='team_scopes', to='control_room.controlroomaccess')),
                ('created_by', models.ForeignKey(blank=True, help_text='Administrator who assigned this scope.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_room_scopes_created', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(help_text='Existing core team whose members/standby are visible.', on_delete=django.db.models.deletion.CASCADE, related_name='control_room_scopes', to='users.team')),
            ],
            options={
                'verbose_name': 'Control Room Team Scope',
                'verbose_name_plural': 'Control Room Team Scopes',
                'ordering': ['team__name'],
            },
        ),
        migrations.AddIndex(
            model_name='controlroomaccess',
            index=models.Index(fields=['is_active'], name='control_roo_is_acti_ecf521_idx'),
        ),
        migrations.AddIndex(
            model_name='controlroomteamscope',
            index=models.Index(fields=['access'], name='control_roo_access__9fc019_idx'),
        ),
        migrations.AddIndex(
            model_name='controlroomteamscope',
            index=models.Index(fields=['team'], name='control_roo_team_id_764930_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='controlroomteamscope',
            unique_together={('access', 'team')},
        ),
    ]
