/**
 * AUTO-GENERATED by scripts/generate_organigrama_meta.py — DO NOT EDIT.
 *
 * Controlled vocabularies for the Organigrama plugin, generated from the
 * canonical Python constants in plugins/organigrama/models.py. The backend
 * remains authoritative for validation and database choices; this module
 * exists so the frontend never re-declares shape/edge/status vocabularies
 * by hand and risk silent drift.
 *
 * Regenerate after changing a backend allowlist:
 *     python scripts/generate_organigrama_meta.py
 * CI verifies freshness with:
 *     python scripts/generate_organigrama_meta.py --check
 */

export const SHAPE_TYPES = [
  "person",
  "position",
  "vacant",
  "external",
  "department",
  "division",
  "team",
  "location",
  "label",
  "section",
  "placeholder",
] as const;

export type ShapeType = (typeof SHAPE_TYPES)[number];

export const EDGE_TYPES = [
  "reports_to",
  "dotted_line",
  "assistant",
  "association",
  "contains",
] as const;

export type EdgeType = (typeof EDGE_TYPES)[number];

export const HIERARCHY_EDGE_TYPES = ["reports_to", "contains"] as const;

export const CONTAINER_SHAPE_TYPES = [
  "section",
  "department",
  "division",
  "team",
  "location",
] as const;

export const CONTAINER_SHAPE_TYPE_SET: ReadonlySet<ShapeType> = new Set(CONTAINER_SHAPE_TYPES);

export const NODE_STATUSES = ["active", "vacant", "planned", "archived"] as const;

export type NodeStatus = (typeof NODE_STATUSES)[number];

export const ROLE_CODES = ["employee", "italian_tl", "albanian_tl", "hr", "cr_admin"] as const;

export type RoleCode = (typeof ROLE_CODES)[number];
