# Generated by Django 5.1.15 on 2026-08-05 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlogfilter',
            index=models.Index(fields=['user'], name='audit_log_a_user_id_349dc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='auditlogfilter',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='audit_log_filter_user_name_unique'),
        ),
    ]
