# Generated by Django 5.2.4 on 2026-08-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0002_auditlogfilter_audit_log_a_user_id_349dc0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('view', 'View'), ('export', 'Export'), ('login', 'Login'), ('logout', 'Logout'), ('other', 'Other'), ('superuser_override_delete', 'Superuser Override Delete')], db_index=True, max_length=50, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='auditlogfilter',
            name='action',
            field=models.CharField(blank=True, choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('view', 'View'), ('export', 'Export'), ('login', 'Login'), ('logout', 'Logout'), ('other', 'Other'), ('superuser_override_delete', 'Superuser Override Delete')], max_length=50, verbose_name='Action'),
        ),
    ]
