#!/usr/bin/env python3
"""Generate Organigrama frontend vocabulary metadata from backend constants.

The backend ``plugins/organigrama/models.py`` is the single source of truth
for controlled vocabularies (shape types, edge types, hierarchy edges,
container shapes, node statuses, role codes). The frontend previously
re-declared these as hand-maintained TypeScript unions and arrays, which
risks silent drift whenever the backend allowlists change.

This generator imports the canonical Python constants and emits a
deterministic TypeScript module at
``frontend/src/plugins/organigrama/generatedMeta.ts``. The frontend imports
the generated arrays/unions instead of re-declaring them, while backend
model constants remain authoritative for validation and database choices.

Usage:

    python scripts/generate_organigrama_meta.py            # write the file
    python scripts/generate_organigrama_meta.py --check     # exit 1 if stale
    python scripts/generate_organigrama_meta.py --output PATH  # custom path

The ``--check`` mode is intended for CI / verification workflows: it prints
a diff and exits non-zero when the generated output differs from the
checked-in file, so drift is caught before merge.
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "frontend" / "src" / "plugins" / "organigrama" / "generatedMeta.ts"

HEADER = """\
/**
 * AUTO-GENERATED by scripts/generate_organigrama_meta.py — DO NOT EDIT.
 *
 * Controlled vocabularies for the Organigrama plugin, generated from the
 * canonical Python constants in plugins/organigrama/models.py. The backend
 * remains authoritative for validation and database choices; this module
 * exists so the frontend never re-declares shape/edge/status vocabularies
 * by hand and risk silent drift.
 *
 * Regenerate after changing a backend allowlist:
 *     python scripts/generate_organigrama_meta.py
 * CI verifies freshness with:
 *     python scripts/generate_organigrama_meta.py --check
 */
"""

# Match the project's Prettier print width (frontend/.prettierrc).
PRETTIER_PRINT_WIDTH = 100


def _ts_const(name: str, values, *, type_annotation: str = "") -> str:
    """Render ``export const NAME = [...] as const;`` Prettier-compliantly."""
    single_array = ", ".join(f'"{v}"' for v in values)
    prefix = f"export const {name} = ["
    closing = f"] as const;{type_annotation}"
    single_line = prefix + single_array + closing
    if len(single_line) <= PRETTIER_PRINT_WIDTH:
        return single_line
    # Multi-line with trailing comma (Prettier es5). Closing bracket on its
    # own line, aligned with the ``export`` keyword.
    lines = [prefix]
    for v in values:
        lines.append(f'  "{v}",')
    lines.append(closing)
    return "\n".join(lines)


def render_meta(
    shape_types,
    edge_types,
    hierarchy_edge_types,
    container_shape_types,
    node_statuses,
    role_codes,
) -> str:
    lines = [HEADER]
    lines.append(_ts_const("SHAPE_TYPES", shape_types))
    lines.append("")
    lines.append("export type ShapeType = (typeof SHAPE_TYPES)[number];")
    lines.append("")
    lines.append(_ts_const("EDGE_TYPES", edge_types))
    lines.append("")
    lines.append("export type EdgeType = (typeof EDGE_TYPES)[number];")
    lines.append("")
    lines.append(_ts_const("HIERARCHY_EDGE_TYPES", hierarchy_edge_types))
    lines.append("")
    lines.append(_ts_const("CONTAINER_SHAPE_TYPES", container_shape_types))
    lines.append("")
    lines.append(
        "export const CONTAINER_SHAPE_TYPE_SET: ReadonlySet<ShapeType> = new Set(CONTAINER_SHAPE_TYPES);"
    )
    lines.append("")
    lines.append(_ts_const("NODE_STATUSES", node_statuses))
    lines.append("")
    lines.append("export type NodeStatus = (typeof NODE_STATUSES)[number];")
    lines.append("")
    lines.append(_ts_const("ROLE_CODES", role_codes))
    lines.append("")
    lines.append("export type RoleCode = (typeof ROLE_CODES)[number];")
    lines.append("")
    return "\n".join(lines)


def load_backend_constants():
    """Import the canonical backend vocabularies (requires Django setup)."""
    # Ensure the repo root is importable so ``config.settings`` resolves
    # when the script is invoked from any working directory.
    repo_root_str = str(REPO_ROOT)
    if repo_root_str not in sys.path:
        sys.path.insert(0, repo_root_str)
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
    import django
    from django.apps import apps

    if not apps.ready:
        django.setup()
    from plugins.organigrama.models import (  # noqa: WPS433 — local import after setup
        SHAPE_TYPES,
        EDGE_TYPES,
        HIERARCHY_EDGE_TYPES,
        CONTAINER_SHAPE_TYPES,
        NODE_STATUS,
        ROLE_CODES,
    )

    return {
        "shape_types": list(SHAPE_TYPES),
        "edge_types": list(EDGE_TYPES),
        "hierarchy_edge_types": list(HIERARCHY_EDGE_TYPES),
        "container_shape_types": list(CONTAINER_SHAPE_TYPES),
        "node_statuses": list(NODE_STATUS),
        "role_codes": list(ROLE_CODES),
    }


def generate() -> str:
    constants = load_backend_constants()
    return render_meta(**constants)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Path to write the generated TypeScript module.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero when the generated output differs from the file.",
    )
    args = parser.parse_args(argv)

    rendered = generate()
    output_path: Path = args.output

    if args.check:
        if not output_path.exists():
            print(f"ERROR: generated metadata missing at {output_path}", file=sys.stderr)
            print("Run: python scripts/generate_organigrama_meta.py", file=sys.stderr)
            return 1
        # Compare bytes so CRLF/LF differences are caught (the generator
        # always emits LF; a checked-in CRLF copy is treated as stale).
        existing = output_path.read_bytes()
        if existing == rendered.encode("utf-8"):
            print(f"OK: {output_path} is up to date.")
            return 0
        print(f"ERROR: {output_path} is stale.", file=sys.stderr)
        print("Run: python scripts/generate_organigrama_meta.py", file=sys.stderr)
        return 1

    output_path.parent.mkdir(parents=True, exist_ok=True)
    # Write with LF newlines so Prettier --check passes on Windows. The
    # rendered string already uses "\n"; encode to bytes to avoid the
    # platform-default CRLF translation of write_text on Windows.
    output_path.write_bytes(rendered.encode("utf-8"))
    try:
        display = output_path.relative_to(REPO_ROOT)
    except ValueError:
        display = output_path
    print(f"Wrote {display}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
