# Generated by Django 5.1.15 on 2026-05-04 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('BULK_APPROVE', 'Bulk Approve'), ('BULK_REJECT', 'Bulk Reject')], max_length=20)),
                ('model_name', models.CharField(choices=[('overtimelog', 'Overtime Log'), ('standbylog', 'Standby Log'), ('holidayrequest', 'Holiday Request'), ('user', 'User'), ('team', 'Team'), ('client', 'Client')], max_length=50)),
                ('object_id', models.CharField(help_text='ID of the affected object', max_length=50)),
                ('object_repr', models.CharField(help_text='String representation of object', max_length=255)),
                ('old_values', models.JSONField(blank=True, help_text='Previous field values', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='New field values', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('extra_data', models.JSONField(blank=True, help_text='Additional context', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='audit_logs_model_n_656046_idx'), models.Index(fields=['user', '-timestamp'], name='audit_logs_user_id_e11c73_idx'), models.Index(fields=['action', '-timestamp'], name='audit_logs_action_f48619_idx')],
            },
        ),
    ]
