# Generated by Django 5.1.15 on 2026-05-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(choices=[('overtimelog', 'Overtime Log'), ('standbylog', 'Standby Log'), ('leaverequest', 'Leave Request'), ('user', 'User'), ('team', 'Team'), ('client', 'Client')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='report_type',
            field=models.CharField(choices=[('overtime', 'Overtime Report'), ('standby', 'Standby Report'), ('leave', 'Leave Report'), ('combined', 'Combined Report'), ('wages', 'Wage Report')], max_length=20),
        ),
    ]
