# Generated by Django 5.1.15 on 2026-08-04 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_pushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('own_leave_submitted', 'My leave submitted'), ('own_leave_updated', 'My leave approved or rejected'), ('own_leave_edited', 'My leave edited'), ('own_overtime_submitted', 'My overtime submitted'), ('own_overtime_updated', 'My overtime approved or rejected'), ('own_standby_submitted', 'My standby submitted'), ('own_standby_updated', 'My standby approved or rejected'), ('team_action_required', 'Team submissions needing action'), ('team_leave_deleted', 'Team leave requests deleted')], max_length=40)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_type'],
                'constraints': [models.UniqueConstraint(fields=('user', 'event_type'), name='notifications_user_event_preference_unique')],
            },
        ),
    ]
