# Generated by Django 5.2.4 on 2026-08-09 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_idempotencyrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='event_type',
            field=models.CharField(choices=[('own_leave_submitted', 'My leave submitted'), ('own_leave_updated', 'My leave approved or rejected'), ('own_leave_edited', 'My leave edited'), ('own_overtime_submitted', 'My overtime submitted'), ('own_overtime_updated', 'My overtime approved or rejected'), ('own_standby_submitted', 'My standby submitted'), ('own_standby_updated', 'My standby approved or rejected'), ('team_period_finalized', 'My team period finalized'), ('team_action_required', 'Team submissions needing action'), ('team_leave_deleted', 'Team leave requests deleted')], max_length=40),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key__isnull', False)), fields=('user', 'dedupe_key'), name='notifications_user_dedupe_unique'),
        ),
    ]
