# Generated by Django 5.2.17 on 2026-09-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notificationeventtypeconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationEventTypeConfig',
        ),
    ]
