# Generated by Django 5.2.17 on 2026-09-23 17:33

from django.db import migrations, models


EVENT_TYPES = [
    'own_leave_submitted', 'own_leave_updated', 'own_leave_edited',
    'own_overtime_submitted', 'own_overtime_updated',
    'own_standby_submitted', 'own_standby_updated', 'team_period_finalized',
    'team_action_required', 'team_leave_deleted',
]


def seed_enabled_types(apps, schema_editor):
    Config = apps.get_model('notifications', 'NotificationEventTypeConfig')
    for event_type in EVENT_TYPES:
        Config.objects.get_or_create(event_type=event_type, defaults={'is_enabled': True})


def unseed_types(apps, schema_editor):
    apps.get_model('notifications', 'NotificationEventTypeConfig').objects.filter(
        event_type__in=EVENT_TYPES
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_delete_notificationeventtypeconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEventTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('own_leave_submitted', 'My leave submitted'), ('own_leave_updated', 'My leave approved or rejected'), ('own_leave_edited', 'My leave edited'), ('own_overtime_submitted', 'My overtime submitted'), ('own_overtime_updated', 'My overtime approved or rejected'), ('own_standby_submitted', 'My standby submitted'), ('own_standby_updated', 'My standby approved or rejected'), ('team_period_finalized', 'My team period finalized'), ('team_action_required', 'Team submissions needing action'), ('team_leave_deleted', 'Team leave requests deleted')], max_length=40, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(seed_enabled_types, unseed_types),
    ]
