# Generated by Django 5.2.17 on 2026-10-01 10:09

import plugins.notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_notificationeventtypeconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationeventtypeconfig',
            name='event_type',
            field=models.CharField(choices=plugins.notifications.models.event_type_choices, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='event_type',
            field=models.CharField(choices=plugins.notifications.models.event_type_choices, max_length=40),
        ),
    ]
