# Generated by Django 5.1.15 on 2026-05-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Internal Name')),
                ('verbose_name', models.CharField(max_length=200, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('version', models.CharField(max_length=20, verbose_name='Version')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plugin',
                'verbose_name_plural': 'Plugins',
                'ordering': ['verbose_name'],
            },
        ),
    ]
