# Generated by Django 5.1.15 on 2026-06-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0007_plugin_permission_system'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pluginpermission',
            new_name='plugin_perm_plugin__0bb612_idx',
            old_name='plugin_perm_plugin__idx',
        ),
        migrations.RenameIndex(
            model_name='pluginpermission',
            new_name='plugin_perm_action_51f9d5_idx',
            old_name='plugin_perm_action_idx',
        ),
        migrations.AddField(
            model_name='pluginpermission',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If checked, all authenticated users will have this permission regardless of roles/groups.', verbose_name='Public Access'),
        ),
    ]
