# Generated by Django 5.2.17 on 2026-10-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # permissions.0005 already created the Role table; depending on 0007
        # would cycle with permissions.0007's own ('plugins', '__latest__').
        ('permissions', '0006_seed_hbpr_role'),
        ('plugins', '0008_rename_plugin_perm_plugin__idx_plugin_perm_plugin__0bb612_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginpermission',
            name='denial_override_roles',
            field=models.ManyToManyField(blank=True, help_text="Elevated roles that keep access even when a denied_role matches (e.g. an HBPR user who is also HR). Never list 'employee' here.", related_name='plugin_permission_denial_overrides', to='permissions.role'),
        ),
        migrations.AddField(
            model_name='pluginpermission',
            name='denied_roles',
            field=models.ManyToManyField(blank=True, help_text='Roles explicitly denied this plugin action (e.g. HBPR-only users on plugins outside their role). Beats is_public and allowed_roles unless a denial_override_role matches.', related_name='plugin_permission_denials', to='permissions.role'),
        ),
    ]
